import React, { useEffect, useRef, useState } from "react";
import { trackStep } from "../../utils/journey";
export default function ShareKit({ data, slug, onClose }) {
  const dialog = useRef(null); const [qr, setQR] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const url = `${window.location.origin}/p/${slug}`;
  const [announcement, setAnnouncement] = useState(`Explore my portfolio${data.title ? ` — ${data.title}` : ""}: ${url}`);
  useEffect(() => { const trigger = document.activeElement; const element = dialog.current; element.showModal(); let active = true; import("qrcode-generator").then(module => { const make = module.default || module; const code = make(0,"M"); code.addData(url); code.make(); const size = code.getModuleCount(); const canvas = document.createElement("canvas"); canvas.width = canvas.height = (size+8)*6; const ctx = canvas.getContext("2d"); ctx.fillStyle = "white"; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle = "black"; for(let y=0;y<size;y++) for(let x=0;x<size;x++) if(code.isDark(y,x)) ctx.fillRect((x+4)*6,(y+4)*6,6,6); if(active) setQR(canvas.toDataURL("image/png")); }).catch(() => { if(active) setError("QR code could not be generated. You can still copy your link."); }); return () => { active = false; element.close(); trigger?.focus(); }; }, [url]);
  const copy = async text => { setError(""); setMessage(""); try { await navigator.clipboard.writeText(text); setMessage("Copied"); trackStep("share"); } catch { setError("Clipboard is unavailable. Select the text below and copy it manually."); } };
  return <dialog ref={dialog} className="completion-dialog" aria-labelledby="sharing-title" onCancel={e => { e.preventDefault(); onClose(); }}><h2 id="sharing-title">Your sharing kit</h2><p>This link opens the published portfolio. Repeat clicks are not unique visitors.</p><label htmlFor="sharing-link">Portfolio link</label><input id="sharing-link" className="form-input" value={url} readOnly /><button type="button" className="btn btn-secondary btn-sm" onClick={() => copy(url)}>Copy portfolio link</button><label htmlFor="sharing-announcement">Edit your announcement</label><textarea id="sharing-announcement" className="form-input" rows={4} value={announcement} onChange={e => setAnnouncement(e.target.value)} /><button type="button" className="btn btn-secondary btn-sm" onClick={() => copy(announcement)}>Copy announcement</button><div className="sharing-images">{qr && <div><img src={qr} alt="QR code for this portfolio" /><a href={qr} download="porty-qr.png" onClick={() => trackStep("share")}>Download QR code</a></div>}{/^data:image\/(jpeg|png);base64,/.test(data.thumbnail || "") && <div><img src={data.thumbnail} alt="Actual portfolio cover" /><a href={data.thumbnail} download="porty-cover.jpg" onClick={() => trackStep("share")}>Download cover image</a></div>}</div>{!data.thumbnail && <p>A cover is generated when the owner next saves this portfolio. External images may prevent capture; sharing the link still works.</p>}{error && <p role="alert" className="form-error">{error}</p>}{message && <p role="status">{message}</p>}<button type="button" className="btn btn-primary" onClick={onClose}>Close sharing kit</button></dialog>;
}
