const assert=require('node:assert/strict');const {chromium}=require('playwright');const path=require('node:path');const {spawn}=require('node:child_process');const fs=require('node:fs');
const output=path.join(__dirname,'artifacts','completion');fs.mkdirSync(output,{recursive:true});
(async()=>{const server=spawn(process.execPath,[path.join(__dirname,'serve-build.cjs')],{env:{...process.env,PORT:'3112'}});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});let browser;let passed=0;
try{browser=await chromium.launch({headless:true,executablePath:process.env.PORTY_CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
const test=async(name,run,auth=true)=>{if(process.env.PORTY_COMPLETION_FILTER && !name.includes(process.env.PORTY_COMPLETION_FILTER))return;const context=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://fonts.gstatic.com/**',r=>r.abort());await context.addInitScript(auth=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...rest){return /webgl/.test(type)?null:original.call(this,type,...rest);};if(auth){localStorage.setItem('token','fixture-token');localStorage.setItem('user',JSON.stringify({id:'owner',name:'Anya'}));}},auth);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await run(page,context);assert.deepEqual(errors,[]);console.log('PASS '+name);passed++;}catch(e){console.log('Alerts:',await page.locator('[role=alert]').allTextContents());console.log('Browser errors:',errors);await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw new Error(name+': '+e.message,{cause:e});}finally{await context.close();}};
const url='http://127.0.0.1:3112';const record={_id:'one',shareSlug:'anya-stable',name:'Anya',title:'Designer',about:'I build interfaces.',theme:'minimalist',skills:['React'],projects:[{title:'Journal',description:'A journal I built.',link:'https://example.com/journal',github:'https://github.com/example/journal',techStack:[]}],experience:[],certifications:[],achievements:[],codingProfiles:[],contact:{email:'anya@example.com'},socialLinks:{},resumeUrl:'https://example.com/resume.pdf',themeColors:{},sectionOrder:['contact','projects','experience','credentials','profiles'],sectionVisibility:{},motion:'subtle',isPublic:true,updatedAt:new Date().toISOString()};
const api=async(page)=>{const stored=structuredClone(record);const writes=[];await page.route('**/api/**',route=>{const request=route.request();const pathname=new URL(request.url()).pathname;const reply=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});if(pathname==='/api/portfolio/capabilities')return reply({data:{layoutStudio:true}});if(pathname==='/api/portfolio/my')return reply({data:[stored]});if(pathname==='/api/portfolio/one'){if(request.method()==='PUT'){Object.assign(stored,request.postDataJSON());writes.push(structuredClone(stored));}return reply({data:stored});}if(pathname==='/api/portfolio'){writes.push(request.postDataJSON());return reply({data:{id:'one',shareSlug:'anya-stable'}},201);}if(pathname.startsWith('/api/portfolio/share/'))return reply({data:stored});if(pathname.startsWith('/api/portfolio/events/')){writes.push(request.postDataJSON());return reply({success:true});}return reply({error:'Unsupported fixture request'},404);});return{stored,writes};};
const overflow=async page=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
await test('Guest trial retains original content across reload and sign-in, without automatic publication',async page=>{
await api(page);await page.goto(url+'/try');await page.getByLabel('Your name',{exact:true}).fill('Guest Anya');await page.getByLabel('A little about you',{exact:true}).fill('I design community tools.');await page.getByLabel('Project title',{exact:true}).fill('Guest journal');await page.getByLabel('What did you contribute?',{exact:true}).fill('I built the editor.');await page.getByLabel('Explore all 41 themes').selectOption('pixel-art');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('porty:guest:v1')||'{}').name==='Guest Anya');await page.reload();assert.equal(await page.getByLabel('Your name',{exact:true}).inputValue(),'Guest Anya');assert.equal(await page.getByLabel('Explore all 41 themes').inputValue(),'pixel-art');await overflow(page);await page.getByRole('link',{name:'Sign in & continue'}).click();await page.route('**/api/auth/login',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({token:'fixture-token',user:{id:'owner',name:'Anya'}})}));await page.getByLabel('Email',{exact:true}).fill('anya@example.com');await page.getByLabel('Password',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'Sign In →'}).click();await page.waitForURL('**/builder');await page.getByRole('button',{name:'Continue guest work'}).click();assert.equal(await page.getByPlaceholder('John Doe').inputValue(),'Guest Anya');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();assert.equal(await page.getByRole('switch').getAttribute('aria-checked'),'false');},false);
await test('Reviewed TXT, DOCX and PDF resume imports apply only selected corrected fields',async page=>{
await api(page);await page.goto(url+'/builder/one');await page.getByText('Start from a resume · optional',{exact:true}).click();await page.getByLabel('Choose resume',{exact:true}).setInputFiles({name:'resume.txt',mimeType:'text/plain',buffer:Buffer.from('Resume Person\nresume@example.com\nSummary\nI built a student journal.\nSkills\nReact, CSS\nProjects\nJournal: A writing space I designed.')});await page.getByRole('heading',{name:'Review before applying'}).waitFor();assert.equal(await page.getByPlaceholder('John Doe').inputValue(),'Anya');await page.getByLabel('Extracted name',{exact:true}).fill('Reviewed Person');await page.getByLabel('Apply name',{exact:true}).check();await page.getByRole('button',{name:'Apply selected information'}).click();assert.equal(await page.getByPlaceholder('John Doe').inputValue(),'Reviewed Person');assert.equal(await page.getByPlaceholder('Write a compelling bio…').inputValue(),'I build interfaces.');await overflow(page);
// A real zipped Word file tests the browser parser rather than replacing it with a mock.
const docx=Buffer.from(require('./fixtures/resume.cjs').docx,'base64');await page.getByLabel('Choose resume',{exact:true}).setInputFiles({name:'resume.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:docx});await page.getByRole('heading',{name:'Review before applying'}).waitFor();assert.match(await page.getByLabel('Or paste resume text').inputValue(),/Word Resume Person/);
await page.getByRole('button',{name:'Dismiss import'}).click();
await page.getByLabel('Choose resume',{exact:true}).setInputFiles({name:'resume.pdf',mimeType:'application/pdf',buffer:Buffer.from(require('./fixtures/resume.cjs').pdf,'base64')});
await page.getByRole('heading',{name:'Review before applying'}).waitFor();assert.match(await page.getByLabel('Or paste resume text').inputValue(),/PDF Resume Person/);
});
await test('Undo, redo, section visibility/order and new profile settings round trip through an explicit save',async page=>{
await page.addInitScript(()=>{const decode=HTMLImageElement.prototype.decode;window.__delayedCoverDecodes=0;HTMLImageElement.prototype.decode=function(){if(/^data:image\/svg\+xml/.test(this.src)){window.__delayedCoverDecodes++;return new Promise(resolve=>setTimeout(resolve,1200)).then(()=>decode.call(this));}return decode.call(this);};});
const fixture=await api(page);await page.goto(url+'/builder/one');await page.getByPlaceholder('John Doe').fill('Updated Anya');await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await page.getByPlaceholder('John Doe').inputValue(),'Anya');await page.getByRole('button',{name:'Redo',exact:true}).click();assert.equal(await page.getByPlaceholder('John Doe').inputValue(),'Updated Anya');await page.getByLabel('Availability',{exact:true}).fill('Seeking an internship');await page.getByLabel('Show my location',{exact:true}).uncheck();await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Motion preference').selectOption('expressive');await page.getByLabel('Experience',{exact:true}).uncheck();await page.getByRole('button',{name:'Move projects section up',exact:true}).click();await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByText('Saved at',{exact:false}).waitFor();assert.equal(fixture.writes.length,1);assert.equal(fixture.stored.motion,'expressive');assert.equal(fixture.stored.sectionVisibility.experience,false);assert.equal(fixture.stored.sectionOrder[0],'projects');assert.equal(fixture.stored.availability,'Seeking an internship');assert.equal(fixture.stored.showLocation,false);assert.match(fixture.stored.thumbnail,/^data:image\/jpeg;base64,/);assert.ok(await page.evaluate(()=>window.__delayedCoverDecodes>0),'Save capture must survive a render longer than the background timer');await overflow(page);});
await test('Existing relative image addresses save while image data cannot be used as a resume link',async page=>{
const fixture=await api(page);fixture.stored.avatarUrl='/sample-portrait.png';fixture.stored.projects[0].image='/sample-project.png';await page.goto(url+'/builder/one');await page.getByLabel('Resume link',{exact:true}).fill('data:image/png;base64,aGVsbG8=');await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByRole('alert').filter({hasText:'Use a complete http or https address'}).waitFor();assert.equal(fixture.writes.length,0);await page.getByLabel('Resume link',{exact:true}).fill('https://example.com/resume.pdf');await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByText('Saved at',{exact:false}).waitFor();assert.equal(fixture.writes.length,1);assert.equal(fixture.stored.avatarUrl,'/sample-portrait.png');assert.equal(fixture.stored.projects[0].image,'/sample-project.png');
});
await test('Sharing kit generates a real QR, editable announcement and accessible modal; clicks are measured',async page=>{
const fixture=await api(page);await page.goto(url+'/p/anya-stable');await page.getByRole('button',{name:'Portfolio tools',exact:true}).click();await page.getByRole('button',{name:'Sharing kit',exact:true}).click();await page.getByRole('dialog',{name:'Your sharing kit'}).waitFor();const qr=page.getByRole('img',{name:'QR code for this portfolio'});await qr.waitFor();assert.match(await qr.getAttribute('src'),/^data:image\/png;base64,/);await page.getByLabel('Edit your announcement').fill('My reviewed announcement');await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.getByRole('button',{name:'Sharing kit',exact:true}).evaluate(el=>el===document.activeElement),true);await page.getByRole('link',{name:'View project',exact:false}).first().click({noWaitAfter:true});await page.waitForFunction(()=>true);await page.getByText('Quick profile',{exact:true}).click();await page.getByRole('link',{name:'Resume',exact:true}).last().click({noWaitAfter:true});await page.waitForTimeout(100);assert.ok(fixture.writes.some(e=>e.type==='project'));assert.ok(fixture.writes.some(e=>e.type==='resume'));await overflow(page);});
await test('Recovery and password visibility preserve the entered email and report provider failures',async page=>{
await page.route('**/api/auth/forgot-password',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Recovery email could not be sent. Please try again later.'})}));await page.goto(url+'/login');await page.getByLabel('Password',{exact:true}).fill('my-test-password');await page.getByRole('button',{name:'Show password',exact:true}).click();assert.equal(await page.getByLabel('Password',{exact:true}).getAttribute('type'),'text');await page.getByRole('link',{name:'Forgot password?',exact:true}).click();await page.getByLabel('Email',{exact:true}).fill('anya@example.com');await page.getByRole('button',{name:'Send recovery code',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByLabel('Email',{exact:true}).inputValue(),'anya@example.com');await overflow(page);},false);
await test('Showcase uses only settings, never the original author identity, when starting a new trial',async page=>{
await page.route('**/api/portfolio/showcase',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({data:[{name:'Original Creator',title:'Original role',theme:'victorian',themeColors:{bg:'#241C2B',text:'#F0E5CE',accent:'#D7BB84'},shareSlug:'creator'}]})}));await page.goto(url+'/showcase');await page.getByRole('link',{name:'Use this style',exact:true}).click();assert.equal(await page.getByLabel('Your name',{exact:true}).inputValue(),'');assert.equal(await page.getByLabel('Explore all 41 themes').inputValue(),'victorian');},false);
await test('Exploratory themes retain direct browsing, real command replies, slide controls and pause behavior',async page=>{
const fixture=await api(page);
for(const theme of ['ai-assistant','blueprint','terminal-os','interactive-3d','pixel-art','spotify-wrapped','netflix-portfolio','hacker-matrix']){
 fixture.stored.theme=theme;fixture.stored.motion='expressive';await page.goto(url+'/p/anya-stable');const portfolio=page.locator('.portfolio-v4');await portfolio.locator('h1').waitFor();
 if(theme==='ai-assistant'){await portfolio.getByLabel('Ask about this portfolio').fill('work experience');await portfolio.getByRole('button',{name:'Ask',exact:true}).click();await portfolio.getByText('No experience details have been supplied.').waitFor();await portfolio.getByRole('button',{name:'Projects',exact:true}).click();await portfolio.locator('.ex-answer').getByText('Journal — A journal I built.',{exact:true}).waitFor();await portfolio.getByRole('link',{name:'Browse this section'}).click();assert.equal(new URL(page.url()).hash,'#pf-work');}
 if(['blueprint','terminal-os'].includes(theme)){const nav=portfolio.locator('.ex-sheets');const name=theme==='terminal-os'?'projects.md':'Projects';await nav.getByRole('link',{name,exact:true}).click();await page.waitForTimeout(100);assert.equal(await nav.getByRole('link',{name,exact:true}).getAttribute('aria-current'),'location');}
 if(['interactive-3d','pixel-art'].includes(theme)){await portfolio.getByRole('link',{name:'Explore projects',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(new URL(page.url()).hash,'#pf-work');if(theme==='interactive-3d'){await portfolio.getByRole('button',{name:'Reading view',exact:true}).click();assert.equal(await portfolio.locator('.ex-reading').count(),1);}}
 if(theme==='spotify-wrapped'){await portfolio.getByRole('button',{name:'Next story',exact:true}).click();await portfolio.locator('.ex-slides').getByRole('heading',{name:'Journal',exact:true}).waitFor();await portfolio.getByRole('button',{name:'Previous story',exact:true}).click();await portfolio.locator('.ex-slides').getByRole('heading',{name:'My perspective',exact:true}).waitFor();assert.equal(await portfolio.locator('.pf-project').count(),1);}
 if(theme==='hacker-matrix'){await page.emulateMedia({reducedMotion:'no-preference'});await portfolio.getByRole('button',{name:'Animate rain',exact:true}).click();assert.equal(await portfolio.locator('.ex-rain').count(),1);await portfolio.getByRole('button',{name:'Pause rain',exact:true}).click();assert.equal(await portfolio.locator('.ex-rain').count(),0);await page.emulateMedia({reducedMotion:'reduce'});}
 await overflow(page);
}
});
await test('Audience propagation reports partial failure and leaves unselected project data unchanged',async page=>{
const versions=[{...structuredClone(record),_id:'one',name:'Source Anya',contact:{email:'source@example.com'}},{...structuredClone(record),_id:'two',name:'Client version',contact:{email:'client@example.com'}},{...structuredClone(record),_id:'three',name:'Recruiter version',contact:{email:'recruiter@example.com'}}];let attempts=[];
await page.route('**/api/portfolio/**',route=>{const req=route.request(),pathname=new URL(req.url()).pathname;const reply=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});if(pathname==='/api/portfolio/capabilities')return reply({data:{layoutStudio:true}});if(pathname==='/api/portfolio/my')return reply({data:versions});const item=versions.find(v=>pathname===`/api/portfolio/${v._id}`);if(item){if(req.method()==='PUT'){attempts.push(req.postDataJSON());if(item._id==='three')return reply({error:'Fixture save failed'},503);Object.assign(item,req.postDataJSON());}return reply({data:item});}return reply({error:'Unsupported request'},404);});
await page.goto(url+'/dashboard');await page.getByText('Reuse profile information & create audience versions',{exact:true}).click();await page.getByLabel('Source portfolio',{exact:true}).selectOption('one');await page.getByLabel('Contact information',{exact:true}).check();await page.getByLabel('Client version · Public (changes go live)',{exact:true}).check();await page.getByLabel('Recruiter version · Public (changes go live)',{exact:true}).check();await page.getByRole('button',{name:'Apply selected fields to 2 versions',exact:true}).click();await page.getByText('1 version updated.',{exact:false}).waitFor();await page.getByText('Recruiter version: Fixture save failed',{exact:true}).waitFor();await page.waitForTimeout(200);assert.equal(await page.getByText('Recruiter version: Fixture save failed',{exact:true}).isVisible(),true);assert.equal(versions[1].contact.email,'source@example.com');assert.equal(versions[2].contact.email,'recruiter@example.com');assert.equal(attempts.length,2);assert.equal(attempts[0].projects,undefined);await overflow(page);
});
await test('Trash can be loaded and restored without exposing a dead public link',async page=>{
let trashed=true;await page.route('**/api/portfolio/**',route=>{const req=route.request(),pathname=new URL(req.url()).pathname;const reply=data=>route.fulfill({contentType:'application/json',body:JSON.stringify(data)});if(pathname==='/api/portfolio/capabilities')return reply({data:{layoutStudio:true}});if(pathname==='/api/portfolio/my')return reply({data:trashed?[]:[record]});if(pathname==='/api/portfolio/trash')return reply({data:trashed?[{_id:'one',name:'Anya',deletedAt:new Date().toISOString()}]:[]});if(pathname==='/api/portfolio/one/restore'){trashed=false;return reply({success:true,data:record});}return reply({success:true});});await page.goto(url+'/dashboard');await page.getByText('Trash · restore within 30 days',{exact:true}).click();await page.getByRole('button',{name:'Load Trash',exact:true}).click();await page.getByRole('button',{name:'Restore',exact:true}).click();await page.getByRole('link',{name:'Edit',exact:true}).waitFor();assert.equal(trashed,false);await overflow(page);
});
await test('Image crop is reviewed before replacing a portrait and can be canceled without changing the saved image',async page=>{
const fixture=await api(page);await page.goto(url+'/builder/one');const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=800;canvas.height=400;const ctx=canvas.getContext('2d');ctx.fillStyle='#aa4455';ctx.fillRect(0,0,800,400);ctx.fillStyle='#ffdddd';ctx.fillRect(100,100,200,200);return canvas.toDataURL('image/png').split(',')[1];});const input=page.locator('input[type=file][accept="image/*"]').first();await input.setInputFiles({name:'portrait.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('dialog',{name:'Crop image'}).waitFor();assert.equal(await page.getByPlaceholder('https://github.com/user.png').inputValue(),'');await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.getByPlaceholder('https://github.com/user.png').inputValue(),'');await input.setInputFiles({name:'portrait.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('dialog',{name:'Crop image'}).waitFor();await page.getByLabel('Zoom',{exact:true}).focus();await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'Apply crop',exact:true}).click();await page.getByRole('dialog',{name:'Crop image'}).waitFor({state:'hidden'});assert.match(await page.getByPlaceholder('https://github.com/user.png').inputValue(),/^data:image\/jpeg;base64,/);assert.equal(fixture.writes.length,0);await overflow(page);
});
console.log(`${passed} completion scenarios passed.`);
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e.stack);if(e.cause)console.error(e.cause.stack);process.exitCode=1;});
