const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path');
const catalog=require('../../backend/themeCatalog.json');
const output=path.join(__dirname,'artifacts','theme-discovery');fs.mkdirSync(output,{recursive:true});
const image='data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="900" height="600"><rect width="900" height="600" fill="#223244"/><circle cx="630" cy="220" r="170" fill="#dda778"/><path d="M70 400H780" stroke="#f4eddb" stroke-width="20"/><text x="70" y="180" fill="#f4eddb" font-size="60">Project screenshot</text></svg>').toString('base64');
const fixture={_id:'one',shareSlug:'research-fixture',name:'Anya Karri',title:'Designer & developer',about:'I build thoughtful digital experiences. These are isolated sample projects for review.',theme:'minimalist',motion:'expressive',layoutSettings:{},skills:['Design','React','Python'],themeColors:{},avatarUrl:image,projects:[{title:'Community journal',description:'A journal for a student community.',techStack:['React','Design'],problem:'Notes were difficult to find.',contribution:'I designed and built the interface.',process:'Tested a prototype with classmates.',outcome:'Presented the prototype at our review.',image,link:'https://example.com/journal',github:'https://github.com/example/journal',featured:true},{title:'Field notes',description:'A research notebook.',techStack:['Python'],image:'',link:'https://example.com/notes',github:'https://github.com/example/notes'},{title:'Study planner',description:'A timetable prototype.',techStack:['React'],image:'',link:'https://example.com/planner',github:'https://github.com/example/planner'}],experience:[{role:'Design intern',company:'Student studio',duration:'May–June 2026'}],certifications:[],achievements:[],codingProfiles:[],contact:{email:'anya@example.com'},socialLinks:{},sectionOrder:['projects','experience','credentials','profiles','contact'],sectionVisibility:{},isPublic:true};
(async()=>{
const server=spawn(process.execPath,[path.join(__dirname,'serve-build.cjs')],{env:{...process.env,PORT:'3116'}});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});
let browser,page,cases=0;
try {
browser=await chromium.launch({headless:true,executablePath:process.env.PORTY_CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://fonts.gstatic.com/**',r=>r.abort());
await context.addInitScript(()=>{localStorage.setItem('token','fixture-token');localStorage.setItem('user',JSON.stringify({id:'owner',name:'Anya'}));});
page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let active=structuredClone(fixture),writes=0;
await page.route('**/api/**',r=>{const req=r.request(),p=new URL(req.url()).pathname;if(['PUT','POST','DELETE'].includes(req.method())&&/^\/api\/portfolio(?:\/one)?$/.test(p))writes++;return r.fulfill({contentType:'application/json',body:JSON.stringify({success:true,data:p.endsWith('/my')?[active]:active})});});
const open=async()=>{await page.goto('http://127.0.0.1:3116/p/research-fixture');await page.locator('.portfolio-v4 h1').waitFor();};
const overflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,active.theme+' overflow');
for(const theme of catalog.map(t=>t.id).filter(id=>!process.env.PORTY_DISCOVERY_THEMES || process.env.PORTY_DISCOVERY_THEMES.split(",").includes(id)))for(const width of [390,1440]){
 active=structuredClone({...fixture,theme});await page.setViewportSize({width,height:1000});await open();await overflow();
 const search=page.getByRole('searchbox',{name:'Find a project'});
 await search.fill('not a real project');await page.getByText('0 of 3 projects · Try another search.',{exact:true}).waitFor();assert.equal(await page.locator('#pf-work .pf-project').count(),0);assert.equal(await page.getByRole('heading',{name:'Design intern',exact:true}).count(),1);
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();await page.getByLabel('Technology',{exact:true}).selectOption('Python');await page.getByRole('heading',{name:'Field notes',exact:true}).waitFor();assert.equal(await page.locator('#pf-work .pf-project').count(),1);
 await search.fill('STUDY');assert.equal(await page.locator('#pf-work .pf-project').count(),0);await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.equal(await page.locator('#pf-work .pf-project').count(),3);
 await page.getByRole('button',{name:'Reading index',exact:true}).click();const grid=page.locator('#pf-work .pf-project-grid');assert.equal(await grid.evaluate(el=>getComputedStyle(el).display),'grid');await overflow();
 const button=page.getByRole('button',{name:'Explore Community journal',exact:true});await button.click();const dialog=page.getByRole('dialog',{name:'Community journal',exact:true});await dialog.waitFor();assert.equal(await page.locator('.pf-project-dialog').evaluate(el=>el.matches(':modal')),true);await dialog.getByText('Notes were difficult to find.',{exact:true}).waitFor();assert.equal(await dialog.getByRole('link',{name:'Visit project',exact:false}).getAttribute('href'),fixture.projects[0].link);assert.equal(await dialog.getByRole('link',{name:'View source code',exact:false}).getAttribute('href'),fixture.projects[0].github);
 await dialog.getByRole('button',{name:'Next project',exact:false}).click();await page.getByRole('dialog',{name:'Field notes',exact:true}).waitFor();assert.equal(await page.locator('.pf-detail-story').count(),0);await page.getByRole('button',{name:'Previous project',exact:false}).click();await page.getByRole('dialog',{name:'Community journal',exact:true}).waitFor();
 for(let i=0;i<9;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>Boolean(document.activeElement.closest('.pf-project-dialog'))),true);}
 if(['minimalist','scrapbook','surrealism','terminal-os','product-showcase','museum','scroll-cinema'].includes(theme)){await page.locator('.pf-project-dialog').screenshot({path:path.join(output,`${theme}-story-${width}.png`)});}
 await page.keyboard.press('Escape');await page.locator('dialog[open]').waitFor({state:'hidden'});await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Explore Community journal');assert.equal(await button.evaluate(el=>el===document.activeElement),true);assert.notEqual(await page.evaluate(()=>document.documentElement.style.overflow),'hidden');
 await page.getByRole('button',{name:'Theme gallery',exact:true}).click();await overflow();assert.deepEqual(await page.locator('#pf-work .pf-project-links a').evaluateAll(nodes=>nodes.map(n=>n.href).sort()),fixture.projects.flatMap(p=>[p.link,p.github]).sort());
 if(['minimalist','scrapbook','surrealism','terminal-os','product-showcase','museum','scroll-cinema'].includes(theme)){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(output,`${theme}-hero-${width}.png`)});await page.locator('#pf-work .pf-project-grid').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,`${theme}-work-${width}.png`)});}
 assert.deepEqual(errors,[]);cases++;
}
console.log(`PASS ${cases} theme/viewport cases: search, combined filters, reset, index, project stories, keyboard containment, Escape/focus restoration and real destinations`);
active=structuredClone({...fixture,theme:'bento',projects:Array.from({length:8},(_,i)=>({...fixture.projects[i%3],title:'Project '+i}))});await open();assert.equal(await page.locator('#pf-work .pf-project').count(),4);await page.getByRole('button',{name:'Reading index',exact:true}).click();assert.equal(await page.locator('#pf-work .pf-project').count(),8);await page.getByLabel('Technology',{exact:true}).selectOption('Python');assert.equal(await page.locator('#pf-work .pf-project').count(),3);await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.equal(await page.locator('#pf-work .pf-project').count(),8);await page.getByRole('button',{name:'Theme gallery',exact:true}).click();assert.equal(await page.locator('#pf-work .pf-project').count(),4);console.log('PASS Bento filtering and reading view include projects beyond the initial four');
active=structuredClone({...fixture,theme:'scrapbook',projects:[{...fixture.projects[0],image:'/missing.png'}]});await page.route('**/missing.png',r=>r.fulfill({status:404,body:''}));await open();await page.getByRole('button',{name:'Explore Community journal',exact:true}).click();await page.getByText('Screenshot unavailable. The project details and links are still available below.',{exact:true}).waitFor();assert.equal(await page.getByRole('dialog').getByRole('link').count(),2);await page.getByRole('button',{name:'Close project',exact:true}).click();console.log('PASS Project viewer retains content and links after image failure');
active=structuredClone(fixture);await page.goto('http://127.0.0.1:3116/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Minimalist');await page.getByRole('button',{name:'Preview Minimalist',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Interact with preview',exact:true}).click();const frame=page.frameLocator('iframe[title="Minimalist theme preview"]');await frame.getByRole('button',{name:'Explore Community journal',exact:true}).click();await frame.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await frame.locator('dialog[open]').waitFor({state:'hidden'});assert.equal(await page.getByRole('dialog').count(),1);await frame.getByRole('button',{name:'Explore Community journal',exact:true}).focus();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});console.log('PASS Nested project viewer Escape closes the story before closing the theme modal');
await page.goto('http://127.0.0.1:3116/try');await page.getByLabel('Your name',{exact:true}).fill('Anya');await page.getByLabel('A little about you',{exact:true}).fill('I design and build prototypes.');await page.getByLabel('Project title',{exact:true}).fill('First trial project');await page.getByRole('button',{name:'Add another project',exact:true}).click();await page.getByLabel('Project 2 title',{exact:true}).fill('Second trial project');await page.getByLabel('Explore all 41 themes',{exact:true}).selectOption('minimalist');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('porty:guest:v1')||'{}').projects?.[1]?.title==='Second trial project');await page.reload();assert.equal(await page.getByLabel('Project 2 title',{exact:true}).inputValue(),'Second trial project');await page.getByRole('button',{name:'Interact with preview',exact:true}).click();const trial=page.frameLocator('iframe[title="Portfolio preview"]');await trial.locator('#pf-work .pf-project').last().waitFor();assert.equal(await trial.locator('#pf-work .pf-project').count(),2);await trial.getByRole('button',{name:'Explore Second trial project',exact:true}).click();await trial.getByRole('dialog',{name:'Second trial project',exact:true}).waitFor();await trial.getByRole('button',{name:'Close project',exact:true}).click();await page.getByRole('button',{name:'Remove trial project 1',exact:true}).click();assert.equal(await page.getByLabel('Project title',{exact:true}).inputValue(),'Second trial project');console.log('PASS Guest multi-project experiments recover after reload, preserve remaining content and open live project stories');
assert.equal(writes,0);assert.deepEqual(errors,[]);console.log('PASS Visitor browsing makes no portfolio writes');
await context.close();
}catch(e){await page?.screenshot({path:path.join(output,"failure.png"),fullPage:true}).catch(()=>{});console.error(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();}
})();
