const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path');
const output=path.join(__dirname,'artifacts','individual-effects');fs.mkdirSync(output,{recursive:true});
const record={_id:'one',shareSlug:'motion-fixture',name:'Anya Karri',title:'Designer & developer',about:'I make practical ideas feel playful. This is supplied test content.',theme:'surrealism',motion:'expressive',layoutSettings:{},themeColors:{},skills:['React','Design'],avatarUrl:'',projects:Array.from({length:3},(_,i)=>({title:['Community journal','Field notes','Study planner'][i],description:'A working prototype I designed and built.',techStack:['React'],link:`https://example.com/project/${i}`,github:`https://github.com/example/project-${i}`,image:''})),experience:[{role:'Design intern',company:'Student studio',duration:'May–June 2026'}],certifications:[],achievements:[],codingProfiles:[],contact:{email:'anya@example.com'},socialLinks:{},sectionOrder:['projects','experience','credentials','profiles','contact'],sectionVisibility:{},isPublic:true};
(async()=>{
const server=spawn(process.execPath,[path.join(__dirname,'serve-build.cjs')],{env:{...process.env,PORT:'3114'}});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});let browser,passed=0,cases=0;
try{
browser=await chromium.launch({headless:true,executablePath:process.env.PORTY_CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
const url='http://127.0.0.1:3114';
const test=async(name,run,viewport={width:1440,height:1000},reduce=false)=>{
if(process.env.PORTY_MOTION_FILTER && !name.includes(process.env.PORTY_MOTION_FILTER))return;
const context=await browser.newContext({viewport,reducedMotion:reduce?'reduce':'no-preference'});await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://fonts.gstatic.com/**',r=>r.abort());await context.addInitScript(()=>{localStorage.setItem('token','fixture-token');localStorage.setItem('user',JSON.stringify({id:'owner',name:'Anya'}));const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...rest){return /webgl/.test(type)?null:original.call(this,type,...rest);};});
const page=await context.newPage();page.setDefaultTimeout(15000);const stored=structuredClone(record),writes=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',r=>{const req=r.request(),p=new URL(req.url()).pathname;const reply=data=>r.fulfill({contentType:'application/json',body:JSON.stringify(data)});if(p==='/api/portfolio/capabilities')return reply({data:{layoutStudio:true}});if(p==='/api/portfolio/one'){if(req.method()==='PUT'){Object.assign(stored,req.postDataJSON());writes.push(req.postDataJSON());}return reply({data:stored});}if(p==='/api/portfolio/my')return reply({data:[stored]});if(p.startsWith('/api/portfolio/share/'))return reply({data:stored});return reply({success:true});});
try{await run(page,stored,writes);assert.deepEqual(errors,[]);console.log('PASS '+name);passed++;}catch(e){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw new Error(name+': '+e.message,{cause:e});}finally{await context.close();}};
const open=async page=>{await page.goto(url+'/p/motion-fixture');await page.locator('.portfolio-v4 h1').waitFor();};
const overflow=async page=>{const excess=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(excess)console.log(await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,theme:document.querySelector(".portfolio-v4").className,elements:[...document.querySelectorAll(".portfolio-v4 *")].filter(el=>el.getBoundingClientRect().right>innerWidth+1).slice(0,8).map(el=>({class:el.className,width:el.getBoundingClientRect().width,scroll:el.scrollWidth}))})));assert.equal(excess,false);};
await test('Theme effects preview, cancel, apply and save preserve content and native layout',async(page,stored,writes)=>{
await page.goto(url+'/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');const card=page.getByRole('button',{name:'Preview Surrealism',exact:true});await card.click();const dialog=page.getByRole('dialog');assert.equal(await dialog.getByText('Liquid orbit',{exact:true}).count(),1);assert.equal(await dialog.getByRole('button',{name:/Creative gallery|Playful deck/}).count(),0);await dialog.getByLabel('Motion preference',{exact:true}).selectOption('subtle');const frame=page.frameLocator('iframe[title="Surrealism theme preview"]');await frame.locator('.pf-motion-subtle').waitFor();await dialog.getByRole('button',{name:'Pause preview',exact:true}).click();await frame.locator('.pf-static').waitFor();await dialog.getByRole('button',{name:'Play preview',exact:true}).click();await frame.locator('.pf-motion-subtle:not(.pf-static)').waitFor();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(writes.length,0);assert.equal(stored.motion,'expressive');await card.click();await page.getByRole('dialog').getByLabel('Motion preference',{exact:true}).selectOption('subtle');await page.getByRole('button',{name:'Apply Theme',exact:true}).click();await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByText('Saved at',{exact:false}).waitFor();assert.equal(writes.length,1);assert.equal(stored.motion,'subtle');assert.deepEqual(stored.layoutSettings,{});assert.deepEqual(stored.projects,record.projects);assert.equal(stored.name,record.name);
}, {width:390,height:900});
await test('Older services preserve unsupported motion drafts while legacy layout settings no longer block native saves',async(page,stored,writes)=>{
stored.layoutSettings={hero:'centered',projects:'rail',typography:'mono'};await page.route('**/api/portfolio/capabilities',r=>r.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:'Not available'})}));await page.goto(url+'/builder/one');await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByText('Saved at',{exact:false}).waitFor();assert.equal(writes.length,1);await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');await page.getByRole('button',{name:'Preview Surrealism',exact:true}).click();await page.getByRole('dialog').getByLabel('Motion preference',{exact:true}).selectOption('none');await page.getByRole('button',{name:'Apply Theme',exact:true}).click();await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByRole('alert').filter({hasText:'cannot save this motion preference yet'}).waitFor();assert.equal(writes.length,1);assert.equal(stored.motion,'expressive');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('porty:draft:v1:owner:one')||'{}').form?.motion==='none');
});
await test('Interactive iframe supports Escape and restores the parent modal trigger focus',async page=>{
await page.goto(url+'/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');const trigger=page.getByRole('button',{name:'Preview Surrealism',exact:true});await trigger.click();await page.getByRole('dialog').getByRole('button',{name:'Interact with preview',exact:true}).click();await page.frameLocator('iframe[title="Surrealism theme preview"]').getByRole('button',{name:'Pause motion',exact:true}).focus();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await trigger.evaluate(el=>el===document.activeElement),true);
});
await test('Desk pointer perspective, visitor pause and dynamic reduced motion work',async(page,stored)=>{
stored.theme='interactive-3d';await open(page);const scene=page.locator('.ex-desk svg');await scene.scrollIntoViewIfNeeded();const box=await scene.boundingBox();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.4);await page.waitForFunction(()=>document.querySelector('.ex-desk svg').classList.contains('pf-pointer-active'));assert.match(await scene.evaluate(el=>getComputedStyle(el).transform),/matrix3d/);assert.equal(await page.locator('#pf-work .pf-pointer-active').count(),0);await page.getByRole('button',{name:'Reading view',exact:true}).click();await scene.hover();assert.equal(await page.locator('.ex-desk .pf-pointer-active').count(),0);assert.equal(await scene.evaluate(el=>getComputedStyle(el).transform),'none');await page.getByRole('button',{name:'Desk view',exact:true}).click();await page.getByRole('button',{name:'Pause motion',exact:true}).click();assert.equal(await page.locator('.pf-pointer-active').count(),0);await page.waitForFunction(()=>document.querySelector('.portfolio-v4').getAnimations({subtree:true}).filter(a=>a.playState==='running').length===0);await page.getByRole('button',{name:'Resume motion',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Reduced motion',exact:true}).waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await page.emulateMedia({reducedMotion:'no-preference'});await page.getByRole('button',{name:'Pause motion',exact:true}).waitFor();await overflow(page);
});
await test('Atmosphere pauses offscreen and when the page is hidden',async(page,stored)=>{
stored.theme='space-explorer';await open(page);await page.locator('.portfolio-v4[data-ambient="running"]').waitFor();await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.locator('.portfolio-v4[data-ambient="paused"]').waitFor();await page.evaluate(()=>scrollTo(0,0));await page.locator('.portfolio-v4[data-ambient="running"]').waitFor();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await page.locator('.pf-resting').waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);
});
await test('Subtle motion has gentle reveals; Still mode keeps content and controls without animation',async(page,stored)=>{
stored.motion='subtle';await open(page);assert.equal(await page.locator('.pf-static').count(),0);await page.locator('#pf-work').scrollIntoViewIfNeeded();assert.equal(await page.locator('.pf-effect-art').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);stored.motion='none';await open(page);assert.equal(await page.locator('.pf-static').count(),1);assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).length),0);
});
await test('Canvas cards drag, move by keyboard, reset and open actual projects',async(page,stored)=>{
stored.theme='infinite-canvas';await open(page);const card=page.getByRole('button',{name:'Arrange Community journal',exact:true});await card.scrollIntoViewIfNeeded();const initial=await card.getAttribute('style');await card.focus();await page.keyboard.press('ArrowRight');assert.notEqual(await card.getAttribute('style'),initial);const box=await card.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+box.height/2+30,{steps:5});await page.mouse.up();await page.getByRole('button',{name:'Reset board',exact:true}).click();assert.equal(await card.getAttribute('style'),initial);await card.focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>{const r=document.querySelector('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').getBoundingClientRect();return r.top<innerHeight && r.bottom>0;});await page.getByRole('button',{name:'Reading view',exact:true}).click();assert.equal(await page.locator('.ex-playground').count(),0);assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);await overflow(page);
});
await test('Canvas direct touch dragging changes positions without losing full project access',async(page,stored)=>{
stored.theme='infinite-canvas';await open(page);const card=page.getByRole('button',{name:'Arrange Community journal',exact:true});const initial=await card.getAttribute('style');await card.evaluate(el=>{const r=el.getBoundingClientRect(),id=9;el.setPointerCapture=()=>{};el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+20,clientY:r.y+20}));el.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+75,clientY:r.y+55}));el.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+75,clientY:r.y+55}));});assert.notEqual(await card.getAttribute('style'),initial);assert.equal(await page.locator('#pf-work .pf-project-links a').count(),6);await overflow(page);
},{width:390,height:900},true);
await test('Pixel explorer responds to controls and counts only visited supplied project paths',async(page,stored)=>{
stored.theme='pixel-art';await open(page);const player=page.locator('.ex-pixel-player');const initial=await player.getAttribute('style');await page.getByRole('button',{name:'Move right',exact:true}).click();assert.notEqual(await player.getAttribute('style'),initial);await page.getByRole('button',{name:'Jump',exact:true}).click();assert.equal(await page.locator('.ex-pixel-jump').count(),1);await page.locator('.ex-pixel-paths').getByRole('link',{name:'◇ Community journal',exact:true}).click();await page.getByText('1 of 3 project paths explored',{exact:true}).waitFor();assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);await page.locator('.ex-pixel-game').scrollIntoViewIfNeeded();await page.locator('.ex-pixel-game').screenshot({path:path.join(output,'pixel-explorer.png')});await overflow(page);
},{width:390,height:900});
await test('Terminal commands and cinema navigation point to supplied content',async(page,stored)=>{
stored.theme='terminal-os';await open(page);await page.getByLabel('Portfolio command',{exact:true}).fill('ls');await page.getByRole('button',{name:'Run command',exact:true}).click();assert.match(await page.locator('.ex-console-output').innerText(),/Community journal/);await page.getByRole('link',{name:'Open section',exact:false}).click();assert.equal(new URL(page.url()).hash,'#pf-work');await page.getByLabel('Portfolio command',{exact:true}).fill('delete everything');await page.getByRole('button',{name:'Run command',exact:true}).click();assert.match(await page.locator('.ex-console-output').innerText(),/Unknown command/);assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);stored.theme='scroll-cinema';await open(page);const scene=page.getByRole('button',{name:'01 / Community journal',exact:true});await scene.click();assert.equal(await scene.getAttribute('aria-pressed'),'true');await overflow(page);
});
await test('All 41 themes keep native layouts under legacy settings and have individual effects',async(page,stored)=>{
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../../backend/themeCatalog.json')));
const layouts=[{}, {hero:'centered',projects:'rail',spacing:'airy',typography:'mono',image:'rounded',hover:'tilt'}];
const directions=new Set(),signatures=new Set();
for(const theme of catalog.map(t=>t.id)) for(const width of [390,1440]) {
 stored.theme=theme;await page.setViewportSize({width,height:1000});let original;
 for(const layout of layouts){stored.layoutSettings=layout;await open(page);await overflow(page);const root=page.locator('.portfolio-v4');assert.equal(await root.getAttribute('data-effect'),theme);assert.equal(await page.locator('[class*="pf-studio-"]').count(),0);assert.equal(await page.locator('.pf-signature-art,.pf-collection-tools,.pf-project-dialog,.pf-explore-project').count(),0);
 const composition=await page.evaluate(()=>['.portfolio-v4','.pf-hero','.portfolio-v4 h1','#pf-work .pf-project-grid, #pf-work .scrapbook-project-grid, #pf-work .editorial-project-grid, #pf-work .product-studies','#pf-work .pf-project-media'].map(selector=>{const el=document.querySelector(selector),s=getComputedStyle(el);return [s.backgroundColor,s.fontFamily,s.fontSize,s.fontWeight,s.display,s.gridTemplateColumns,s.textAlign,s.paddingTop,s.gap,s.aspectRatio,s.borderRadius];}));
 if(original) assert.deepEqual(composition,original,theme+' legacy preferences changed the original layout'); else original=composition;
 assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);const links=await page.locator('#pf-work .pf-project-links a').evaluateAll(elements=>elements.map(el=>el.href).sort());assert.deepEqual(links,record.projects.flatMap(p=>[p.link,p.github]).sort());cases++;
 }
 directions.add(await page.locator('.portfolio-v4').getAttribute('data-effect'));
 const signature=await page.evaluate(()=>{const cover=getComputedStyle(document.querySelector('.pf-project-cover')),glyph=getComputedStyle(document.querySelector('.pf-cover-glyph'));return {material:[cover.backgroundImage,cover.backgroundColor,cover.boxShadow],letter:[glyph.fontFamily,glyph.fontStyle,glyph.textShadow],art:document.querySelector('.pf-effect-art')?.innerHTML||''};});
 signatures.add(JSON.stringify(signature));
 await page.screenshot({path:path.join(output,`${theme}-${width}.png`)});
 await page.getByRole('button',{name:'Pause motion',exact:true}).click();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0,theme+' pause failed');assert.equal(await page.getByRole('heading',{name:record.name,exact:true}).count(),1);
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Reduced motion',exact:true}).waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).length),0,theme+' reduced motion failed');await page.emulateMedia({reducedMotion:'no-preference'});
}
assert.equal(directions.size,41);assert.equal(signatures.size,41,'Every theme must have its own actual visual material/art signature, independent of its name or class.');
}, {width:1440,height:1000});
console.log(`${passed} motion/interaction scenarios and ${cases} native layout cases passed.`);
}finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e.stack);if(e.cause)console.error(e.cause.stack);process.exitCode=1;});
