const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path');
const output=path.join(__dirname,'artifacts','individual-effects');fs.mkdirSync(output,{recursive:true});
const record={_id:'one',shareSlug:'motion-fixture',name:'Anya Karri',title:'Designer & developer',about:'I make practical ideas feel playful. This is supplied test content.',theme:'surrealism',motion:'expressive',layoutSettings:{},themeColors:{},skills:['React','Design'],avatarUrl:'',projects:Array.from({length:3},(_,i)=>({title:['Community journal','Field notes','Study planner'][i],description:'A working prototype I designed and built.',techStack:['React'],link:`https://example.com/project/${i}`,github:`https://github.com/example/project-${i}`,image:''})),experience:[{role:'Design intern',company:'Student studio',duration:'May–June 2026'}],certifications:[],achievements:[],codingProfiles:[],contact:{email:'anya@example.com'},socialLinks:{},sectionOrder:['projects','experience','credentials','profiles','contact'],sectionVisibility:{},isPublic:true};
(async()=>{
const server=spawn(process.execPath,[path.join(__dirname,'serve-build.cjs')],{env:{...process.env,PORT:'3114'}});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});let browser,passed=0,cases=0;
try{
browser=await chromium.launch({headless:true,executablePath:process.env.PORTY_CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
const url='http://127.0.0.1:3114';
const test=async(name,run,viewport={width:1440,height:1000},reduce=false)=>{
if(process.env.PORTY_MOTION_FILTER && !name.includes(process.env.PORTY_MOTION_FILTER))return;
const context=await browser.newContext({viewport,reducedMotion:reduce?'reduce':'no-preference'});await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://fonts.gstatic.com/**',r=>r.abort());await context.addInitScript(()=>{localStorage.setItem('token','fixture-token');localStorage.setItem('user',JSON.stringify({id:'owner',name:'Anya'}));const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...rest){return /webgl/.test(type)?null:original.call(this,type,...rest);};});
const page=await context.newPage();page.setDefaultTimeout(15000);const stored=structuredClone(record),writes=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',r=>{const req=r.request(),p=new URL(req.url()).pathname;const reply=data=>r.fulfill({contentType:'application/json',body:JSON.stringify(data)});if(p==='/api/portfolio/capabilities')return reply({data:{layoutStudio:true}});if(p==='/api/portfolio/one'){if(req.method()==='PUT'){Object.assign(stored,req.postDataJSON());writes.push(req.postDataJSON());}return reply({data:stored});}if(p==='/api/portfolio/my')return reply({data:[stored]});if(p.startsWith('/api/portfolio/share/'))return reply({data:stored});return reply({success:true});});
try{await run(page,stored,writes);assert.deepEqual(errors,[]);console.log('PASS '+name);passed++;}catch(e){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw new Error(name+': '+e.message,{cause:e});}finally{await context.close();}};
const open=async page=>{await page.goto(url+'/p/motion-fixture');await page.locator('.portfolio-v4 h1').waitFor();};
const overflow=async page=>{const excess=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(excess)console.log(await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,theme:document.querySelector(".portfolio-v4").className,elements:[...document.querySelectorAll(".portfolio-v4 *")].filter(el=>el.getBoundingClientRect().right>innerWidth+1).slice(0,8).map(el=>({class:el.className,width:el.getBoundingClientRect().width,scroll:el.scrollWidth}))})));assert.equal(excess,false);};
await test('Theme effects preview, cancel, apply and save preserve content and native layout',async(page,stored,writes)=>{
await page.goto(url+'/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');const card=page.getByRole('button',{name:'Preview Surrealism',exact:true});await card.click();const dialog=page.getByRole('dialog');assert.equal(await dialog.getByText('Liquid orbit',{exact:true}).count(),1);assert.equal(await dialog.getByRole('button',{name:/Creative gallery|Playful deck/}).count(),0);await dialog.getByLabel('Motion preference',{exact:true}).selectOption('subtle');const frame=page.frameLocator('iframe[title="Surrealism theme preview"]');await frame.locator('.pf-motion-subtle').waitFor();await dialog.getByRole('button',{name:'Pause preview',exact:true}).click();await frame.locator('.pf-static').waitFor();await dialog.getByRole('button',{name:'Play preview',exact:true}).click();await frame.locator('.pf-motion-subtle:not(.pf-static)').waitFor();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(writes.length,0);assert.equal(stored.motion,'expressive');await card.click();await page.getByRole('dialog').getByLabel('Motion preference',{exact:true}).selectOption('subtle');await page.getByRole('button',{name:'Apply Theme',exact:true}).click();await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByText('Saved at',{exact:false}).waitFor();assert.equal(writes.length,1);assert.equal(stored.motion,'subtle');assert.deepEqual(stored.layoutSettings,{});assert.deepEqual(stored.projects,record.projects);assert.equal(stored.name,record.name);
}, {width:390,height:900});
await test('Older services preserve unsupported motion drafts while legacy layout settings no longer block native saves',async(page,stored,writes)=>{
stored.layoutSettings={hero:'centered',projects:'rail',typography:'mono'};await page.route('**/api/portfolio/capabilities',r=>r.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:'Not available'})}));await page.goto(url+'/builder/one');await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByText('Saved at',{exact:false}).waitFor();assert.equal(writes.length,1);await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');await page.getByRole('button',{name:'Preview Surrealism',exact:true}).click();await page.getByRole('dialog').getByLabel('Motion preference',{exact:true}).selectOption('none');await page.getByRole('button',{name:'Apply Theme',exact:true}).click();await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByRole('alert').filter({hasText:'cannot save this motion preference yet'}).waitFor();assert.equal(writes.length,1);assert.equal(stored.motion,'expressive');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('porty:draft:v1:owner:one')||'{}').form?.motion==='none');
});
await test('Interactive iframe supports Escape and restores the parent modal trigger focus',async page=>{
await page.goto(url+'/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');const trigger=page.getByRole('button',{name:'Preview Surrealism',exact:true});await trigger.click();await page.getByRole('dialog').getByRole('button',{name:'Interact with preview',exact:true}).click();await page.frameLocator('iframe[title="Surrealism theme preview"]').getByRole('button',{name:'Pause motion',exact:true}).focus();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await trigger.evaluate(el=>el===document.activeElement),true);
});
await test('Desk pointer perspective, visitor pause and dynamic reduced motion work',async(page,stored)=>{
stored.theme='interactive-3d';await open(page);const scene=page.locator('.ex-desk svg');await scene.scrollIntoViewIfNeeded();const box=await scene.boundingBox();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.4);await page.waitForFunction(()=>document.querySelector('.ex-desk svg').classList.contains('pf-pointer-active'));assert.match(await scene.evaluate(el=>getComputedStyle(el).transform),/matrix3d/);assert.equal(await page.locator('#pf-work .pf-pointer-active').count(),0);await page.getByRole('button',{name:'Reading view',exact:true}).click();await scene.hover();assert.equal(await page.locator('.ex-desk .pf-pointer-active').count(),0);assert.equal(await scene.evaluate(el=>getComputedStyle(el).transform),'none');await page.getByRole('button',{name:'Desk view',exact:true}).click();await page.getByRole('button',{name:'Pause motion',exact:true}).click();assert.equal(await page.locator('.pf-pointer-active').count(),0);await page.waitForFunction(()=>document.querySelector('.portfolio-v4').getAnimations({subtree:true}).filter(a=>a.playState==='running').length===0);await page.getByRole('button',{name:'Resume motion',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Reduced motion',exact:true}).waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await page.emulateMedia({reducedMotion:'no-preference'});await page.getByRole('button',{name:'Pause motion',exact:true}).waitFor();await overflow(page);
});
await test('Atmosphere pauses offscreen and when the page is hidden',async(page,stored)=>{
stored.theme='space-explorer';await open(page);await page.locator('.portfolio-v4[data-ambient="running"]').waitFor();await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.locator('.portfolio-v4[data-ambient="paused"]').waitFor();await page.evaluate(()=>scrollTo(0,0));await page.locator('.portfolio-v4[data-ambient="running"]').waitFor();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await page.locator('.pf-resting').waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);
});
await test('Subtle motion has gentle reveals; Still mode keeps content and controls without animation',async(page,stored)=>{
stored.motion='subtle';await open(page);assert.equal(await page.locator('.pf-static').count(),0);await page.locator('#pf-work').scrollIntoViewIfNeeded();assert.equal(await page.locator('.pf-effect-art').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);stored.motion='none';await open(page);assert.equal(await page.locator('.pf-static').count(),1);assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).length),0);
});
await test('Canvas cards drag, move by keyboard, reset and open actual projects',async(page,stored)=>{
stored.theme='infinite-canvas';await open(page);const card=page.getByRole('button',{name:'Arrange Community journal',exact:true});await card.scrollIntoViewIfNeeded();const initial=await card.getAttribute('style');await card.focus();await page.keyboard.press('ArrowRight');assert.notEqual(await card.getAttribute('style'),initial);const box=await card.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+box.height/2+30,{steps:5});await page.mouse.up();await page.getByRole('button',{name:'Reset board',exact:true}).click();assert.equal(await card.getAttribute('style'),initial);await card.focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>{const r=document.querySelector('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').getBoundingClientRect();return r.top<innerHeight && r.bottom>0;});await page.getByRole('button',{name:'Reading view',exact:true}).click();assert.equal(await page.locator('.ex-playground').count(),0);assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);await overflow(page);
});
await test('Canvas direct touch dragging changes positions without losing full project access',async(page,stored)=>{
stored.theme='infinite-canvas';await open(page);const card=page.getByRole('button',{name:'Arrange Community journal',exact:true});const initial=await card.getAttribute('style');await card.evaluate(el=>{const r=el.getBoundingClientRect(),id=9;el.setPointerCapture=()=>{};el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+20,clientY:r.y+20}));el.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+75,clientY:r.y+55}));el.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+75,clientY:r.y+55}));});assert.notEqual(await card.getAttribute('style'),initial);assert.equal(await page.locator('#pf-work .pf-project-links a').count(),6);await overflow(page);
},{width:390,height:900},true);
await test('Pixel explorer responds to controls and counts only visited supplied project paths',async(page,stored)=>{
stored.theme='pixel-art';await open(page);const player=page.locator('.ex-pixel-player');const initial=await player.getAttribute('style');await page.getByRole('button',{name:'Move right',exact:true}).click();assert.notEqual(await player.getAttribute('style'),initial);await page.getByRole('button',{name:'Jump',exact:true}).click();assert.equal(await page.locator('.ex-pixel-jump').count(),1);await page.locator('.ex-pixel-paths').getByRole('link',{name:'◇ Community journal',exact:true}).click();await page.getByText('1 of 3 project paths explored',{exact:true}).waitFor();assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);await page.locator('.ex-pixel-game').scrollIntoViewIfNeeded();await page.locator('.ex-pixel-game').screenshot({path:path.join(output,'pixel-explorer.png')});await overflow(page);
},{width:390,height:900});
await test('Terminal commands and cinema navigation point to supplied content',async(page,stored)=>{
stored.theme='terminal-os';await open(page);await page.getByLabel('Portfolio command',{exact:true}).fill('ls');await page.getByRole('button',{name:'Run command',exact:true}).click();assert.match(await page.locator('.ex-console-output').innerText(),/Community journal/);await page.getByRole('link',{name:'Open section',exact:false}).click();assert.equal(new URL(page.url()).hash,'#pf-work');await page.getByLabel('Portfolio command',{exact:true}).fill('delete everything');await page.getByRole('button',{name:'Run command',exact:true}).click();assert.match(await page.locator('.ex-console-output').innerText(),/Unknown command/);assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);stored.theme='scroll-cinema';await open(page);const scene=page.getByRole('button',{name:'01 / Community journal',exact:true});await scene.click();assert.equal(await scene.getAttribute('aria-pressed'),'true');await overflow(page);
});
await test('Native stories support keyboard, direct featured destinations and distinct transitions',async(page,stored)=>{
 stored.projects[2].featured=true;
 for(const [theme,animation] of [['storybook','fx-page'],['spotify-wrapped','fx-track']]) {
  stored.theme=theme;await open(page);const stories=page.getByRole('region',{name:'Portfolio stories',exact:true});
  await stories.focus();await page.keyboard.press('ArrowRight');await stories.getByRole('heading',{name:'Study planner',exact:true}).waitFor();
  assert.equal(await stories.getByRole('link',{name:'Explore the full story',exact:false}).getAttribute('href'),'#pf-project-1');
  assert.equal(await stories.locator('.ex-slide-content').evaluate(el=>getComputedStyle(el).animationName),animation);
  await stories.getByRole('link',{name:'Explore the full story',exact:false}).click();assert.equal(new URL(page.url()).hash,'#pf-project-1');assert.match(await page.locator(':focus').innerText(),/Study planner/);
  await stories.focus();await page.keyboard.press('End');await stories.getByRole('heading',{name:'Design intern',exact:true}).waitFor();
  await stories.getByRole('link',{name:'Explore the full story',exact:false}).click();assert.equal(new URL(page.url()).hash,'#pf-experience-1');
  await stories.focus();await page.keyboard.press('Home');await stories.getByRole('heading',{name:'My perspective',exact:true}).waitFor();
  await stories.getByRole('button',{name:'Next story',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal(await stories.getByRole('heading',{name:'My perspective',exact:true}).count(),1,'Keys on a nested button must not hijack the story');
  await page.emulateMedia({reducedMotion:'reduce'});await stories.getByRole('button',{name:'Next story',exact:true}).click();assert.equal(await stories.locator('.ex-slide-content').evaluate(el=>el.getAnimations().length),0);await page.emulateMedia({reducedMotion:'no-preference'});
  await stories.screenshot({path:path.join(output,`${theme}-story-refinement.png`)});await overflow(page);
 }
});
await test('Story touch swipes ignore vertical browsing, cancellation and nested controls',async(page,stored)=>{
 stored.theme='storybook';await open(page);const stories=page.locator('.ex-slides');await stories.scrollIntoViewIfNeeded();
 const swipe=async(dx,dy,cancel=false)=>stories.evaluate((el,{dx,dy,cancel})=>{
  el.setPointerCapture=()=>{};const init={bubbles:true,pointerType:'touch',pointerId:7,isPrimary:true,clientX:220,clientY:100};
  el.dispatchEvent(new PointerEvent('pointerdown',init));el.dispatchEvent(new PointerEvent(cancel?'pointercancel':'pointerup',{...init,clientX:220+dx,clientY:100+dy}));
 },{dx,dy,cancel});
 await swipe(-90,130);assert.equal(await stories.getByRole('heading',{name:'My perspective',exact:true}).count(),1);
 await swipe(-90,0,true);assert.equal(await stories.getByRole('heading',{name:'My perspective',exact:true}).count(),1);
 await stories.getByRole('button',{name:'Next story',exact:true}).evaluate(el=>{const init={bubbles:true,pointerType:'touch',pointerId:8,isPrimary:true,clientX:220,clientY:100};el.dispatchEvent(new PointerEvent('pointerdown',init));el.dispatchEvent(new PointerEvent('pointerup',{...init,clientX:120}));});assert.equal(await stories.getByRole('heading',{name:'My perspective',exact:true}).count(),1);
 await swipe(-90,5);await stories.getByRole('heading',{name:'Community journal',exact:true}).waitFor();
 await swipe(90,5);await stories.getByRole('heading',{name:'My perspective',exact:true}).waitFor();await stories.screenshot({path:path.join(output,'storybook-touch-refinement.png')});await overflow(page);
},{width:390,height:900});
await test('Pixel keyboard and featured paths reach their matching project without hijacking buttons',async(page,stored)=>{
 stored.theme='pixel-art';stored.projects[2].featured=true;await open(page);const game=page.getByRole('region',{name:'Pixel explorer',exact:true});
 await game.focus();const player=game.locator('.ex-pixel-player'),initial=await player.getAttribute('style');await page.keyboard.press('ArrowRight');assert.notEqual(await player.getAttribute('style'),initial);await page.keyboard.press('Space');assert.equal(await game.locator('.ex-pixel-jump').count(),1);
 await game.getByRole('button',{name:'Move left',exact:true}).focus();const before=await player.getAttribute('style');await page.keyboard.press('ArrowRight');assert.equal(await player.getAttribute('style'),before);
 await game.getByRole('link',{name:'◇ Field notes',exact:true}).click();assert.equal(new URL(page.url()).hash,'#pf-project-3');assert.match(await page.locator(':focus').innerText(),/Field notes/);await game.getByText('1 of 3 project paths explored',{exact:true}).waitFor();await game.scrollIntoViewIfNeeded();await game.screenshot({path:path.join(output,'pixel-keyboard-refinement.png')});await overflow(page);
},{width:390,height:900});
await test('Netflix collection follows real card widths, swipe positions and responsive boundaries',async(page,stored)=>{
 stored.theme='netflix-portfolio';stored.projects=[...stored.projects,...stored.projects.map(p=>({...p,title:p.title+' II'}))];stored.motion='none';await open(page);
 const controls=page.getByRole('group',{name:'Project collection',exact:true}),prev=controls.getByRole('button',{name:'Previous projects',exact:true}),next=controls.getByRole('button',{name:'Next projects',exact:true}),rail=page.locator('.pf-project-grid');
 for(const width of [390,1440]) {
  await page.setViewportSize({width,height:1000});await rail.evaluate(el=>el.scrollTo({left:0,behavior:'instant'}));await prev.waitFor();await page.waitForFunction(()=>document.querySelector('[aria-label="Project collection"] button').disabled);
  const target=await rail.evaluate(el=>el.children[1].getBoundingClientRect().left-el.getBoundingClientRect().left);await next.click();await page.waitForFunction(target=>Math.abs(document.querySelector('.pf-project-grid').scrollLeft-target)<3,target);
  await rail.evaluate((el,target)=>{el.style.scrollSnapType='none';el.scrollTo({left:target*.45,behavior:'instant'});},target);await next.click();await page.waitForFunction(target=>Math.abs(document.querySelector('.pf-project-grid').scrollLeft-target)<3,target);
  await rail.evaluate(el=>el.scrollTo({left:el.scrollWidth,behavior:'instant'}));await page.waitForFunction(()=>[...document.querySelectorAll('[aria-label="Project collection"] button')].at(-1).disabled);assert.equal(await prev.isDisabled(),false);
  await prev.click();await page.waitForFunction(()=>![...document.querySelectorAll('[aria-label="Project collection"] button')].at(-1).disabled);await overflow(page);
 }
 stored.motion='expressive';await open(page);const second=await rail.evaluate(el=>el.children[1].getBoundingClientRect().left-el.getBoundingClientRect().left);await next.click();await page.waitForFunction(target=>Math.abs(document.querySelector('.pf-project-grid').scrollLeft-target)<3,second);await page.getByRole('button',{name:'Pause motion',exact:true}).click();await prev.click();await page.waitForFunction(()=>document.querySelector('.pf-project-grid').scrollLeft<3);
 await rail.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'netflix-rail-refinement.png')});
});
await test('Subtle mode has no continuous loops across all 41 native effects',async(page,stored)=>{
 stored.motion='subtle';const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../../backend/themeCatalog.json')));
 for(const {id} of catalog) {stored.theme=id;await open(page);if(id==='hacker-matrix')await page.getByRole('button',{name:'Animate rain',exact:true}).click();
  const loops=await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.effect.getTiming().iterations===Infinity).map(a=>a.animationName));assert.deepEqual(loops,[],id+' has a continuous loop in Subtle mode');
 }
});
await test('Product reflection waits until its original screen enters the viewport',async(page,stored)=>{
 stored.theme='product-showcase';stored.about='A supplied long biography. '.repeat(160);await open(page);const device=page.locator('.product-device').first();
 assert.equal(await device.evaluate(el=>el.getAnimations({subtree:true}).some(a=>a.animationName==='fx-reflection')),false);
 await device.scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('.product-device').getAnimations({subtree:true}).some(a=>a.animationName==='fx-reflection'));
 assert.equal(await device.evaluate(el=>el.classList.contains('pf-effect-entered')),true);await overflow(page);
});
await test('Mobile portfolio tools stay compact and support keyboard, outside dismissal and resizing',async(page,stored)=>{
 stored.theme='storybook';await open(page);const toggle=page.getByRole('button',{name:'Portfolio tools',exact:true}),bar=page.locator('.share-bar');
 assert.ok((await bar.boundingBox()).height<=60);assert.equal(await page.getByRole('button',{name:'Copy link',exact:true}).count(),0);
 await toggle.focus();await page.keyboard.press('Enter');assert.equal(await toggle.getAttribute('aria-expanded'),'true');await page.keyboard.press('Tab');assert.equal(await page.getByRole('button',{name:'Sharing kit',exact:true}).evaluate(el=>el===document.activeElement),true);
 await page.keyboard.press('Escape');assert.equal(await toggle.getAttribute('aria-expanded'),'false');assert.equal(await toggle.evaluate(el=>el===document.activeElement),true);
 await toggle.click();await page.locator('.ex-slide-content').click();assert.equal(await toggle.getAttribute('aria-expanded'),'false');
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Copy link',exact:true}).waitFor();assert.equal(await toggle.isVisible(),false);
 await page.locator('.portfolio-v4 h1').click();await page.setViewportSize({width:390,height:900});await toggle.waitFor();assert.ok((await bar.boundingBox()).height<=60);await page.locator('.ex-slides').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'storybook-mobile-tools.png')});await overflow(page);
 for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});await page.waitForFunction(mobile=>document.querySelector('.share-bar-toggle').hidden!==mobile,width<768);await overflow(page);if(width<768)assert.ok((await bar.boundingBox()).height<=60);}
},{width:390,height:900});
await test('All 41 themes keep native layouts under legacy settings and have individual effects',async(page,stored)=>{
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../../backend/themeCatalog.json')));
const layouts=[{}, {hero:'centered',projects:'rail',spacing:'airy',typography:'mono',image:'rounded',hover:'tilt'}];
const directions=new Set(),signatures=new Set();
for(const theme of catalog.map(t=>t.id)) for(const width of [390,1440]) {
 stored.theme=theme;await page.setViewportSize({width,height:1000});let original;
 for(const layout of layouts){stored.layoutSettings=layout;await open(page);await overflow(page);const root=page.locator('.portfolio-v4');assert.equal(await root.getAttribute('data-effect'),theme);assert.equal(await page.locator('[class*="pf-studio-"]').count(),0);assert.equal(await page.locator('.pf-signature-art,.pf-collection-tools,.pf-project-dialog,.pf-explore-project').count(),0);
 const composition=await page.evaluate(()=>['.portfolio-v4','.pf-hero','.portfolio-v4 h1','#pf-work .pf-project-grid, #pf-work .scrapbook-project-grid, #pf-work .editorial-project-grid, #pf-work .product-studies','#pf-work .pf-project-media'].map(selector=>{const el=document.querySelector(selector),s=getComputedStyle(el);return [s.backgroundColor,s.fontFamily,s.fontSize,s.fontWeight,s.display,s.gridTemplateColumns,s.textAlign,s.paddingTop,s.gap,s.aspectRatio,s.borderRadius];}));
 if(original) assert.deepEqual(composition,original,theme+' legacy preferences changed the original layout'); else original=composition;
 assert.equal(await page.locator('#pf-work .pf-project, #pf-work .scrapbook-project, #pf-work .product-study, #pf-work .editorial-project').count(),3);const links=await page.locator('#pf-work .pf-project-links a').evaluateAll(elements=>elements.map(el=>el.href).sort());assert.deepEqual(links,record.projects.flatMap(p=>[p.link,p.github]).sort());cases++;
 }
 directions.add(await page.locator('.portfolio-v4').getAttribute('data-effect'));
 const signature=await page.evaluate(()=>{const cover=getComputedStyle(document.querySelector('.pf-project-cover')),glyph=getComputedStyle(document.querySelector('.pf-cover-glyph'));return {material:[cover.backgroundImage,cover.backgroundColor,cover.boxShadow],letter:[glyph.fontFamily,glyph.fontStyle,glyph.textShadow],art:document.querySelector('.pf-effect-art')?.innerHTML||''};});
 signatures.add(JSON.stringify(signature));
 await page.screenshot({path:path.join(output,`${theme}-${width}.png`)});
 await page.getByRole('button',{name:'Pause motion',exact:true}).click();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0,theme+' pause failed');assert.equal(await page.getByRole('heading',{name:record.name,exact:true}).count(),1);
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Reduced motion',exact:true}).waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).length),0,theme+' reduced motion failed');await page.emulateMedia({reducedMotion:'no-preference'});
}
assert.equal(directions.size,41);assert.equal(signatures.size,41,'Every theme must have its own actual visual material/art signature, independent of its name or class.');
}, {width:1440,height:1000});
console.log(`${passed} motion/interaction scenarios and ${cases} native layout cases passed.`);
}finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e.stack);if(e.cause)console.error(e.cause.stack);process.exitCode=1;});
