const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path');
const output=path.join(__dirname,'artifacts','motion-studio');fs.mkdirSync(output,{recursive:true});
const record={_id:'one',shareSlug:'motion-fixture',name:'Anya Karri',title:'Designer & developer',about:'I make practical ideas feel playful. This is supplied test content.',theme:'surrealism',motion:'expressive',layoutSettings:{},themeColors:{},skills:['React','Design'],avatarUrl:'',projects:Array.from({length:3},(_,i)=>({title:['Community journal','Field notes','Study planner'][i],description:'A working prototype I designed and built.',techStack:['React'],link:`https://example.com/project/${i}`,github:`https://github.com/example/project-${i}`,image:''})),experience:[{role:'Design intern',company:'Student studio',duration:'May–June 2026'}],certifications:[],achievements:[],codingProfiles:[],contact:{email:'anya@example.com'},socialLinks:{},sectionOrder:['projects','experience','credentials','profiles','contact'],sectionVisibility:{},isPublic:true};
(async()=>{
const server=spawn(process.execPath,[path.join(__dirname,'serve-build.cjs')],{env:{...process.env,PORT:'3114'}});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});let browser,passed=0,cases=0;
try{
browser=await chromium.launch({headless:true,executablePath:process.env.PORTY_CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
const url='http://127.0.0.1:3114';
const test=async(name,run,viewport={width:1440,height:1000},reduce=false)=>{
if(process.env.PORTY_MOTION_FILTER && !name.includes(process.env.PORTY_MOTION_FILTER))return;
const context=await browser.newContext({viewport,reducedMotion:reduce?'reduce':'no-preference'});await context.route('https://fonts.googleapis.com/**',r=>r.abort());await context.route('https://fonts.gstatic.com/**',r=>r.abort());await context.addInitScript(()=>{localStorage.setItem('token','fixture-token');localStorage.setItem('user',JSON.stringify({id:'owner',name:'Anya'}));const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...rest){return /webgl/.test(type)?null:original.call(this,type,...rest);};});
const page=await context.newPage(),stored=structuredClone(record),writes=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/api/**',r=>{const req=r.request(),p=new URL(req.url()).pathname;const reply=data=>r.fulfill({contentType:'application/json',body:JSON.stringify(data)});if(p==='/api/portfolio/capabilities')return reply({data:{layoutStudio:true}});if(p==='/api/portfolio/one'){if(req.method()==='PUT'){Object.assign(stored,req.postDataJSON());writes.push(req.postDataJSON());}return reply({data:stored});}if(p==='/api/portfolio/my')return reply({data:[stored]});if(p.startsWith('/api/portfolio/share/'))return reply({data:stored});return reply({success:true});});
try{await run(page,stored,writes);assert.deepEqual(errors,[]);console.log('PASS '+name);passed++;}catch(e){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw new Error(name+': '+e.message,{cause:e});}finally{await context.close();}};
const open=async page=>{await page.goto(url+'/p/motion-fixture');await page.locator('.portfolio-v4 h1').waitFor();};
const overflow=async page=>{const excess=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(excess)console.log(await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,theme:document.querySelector(".portfolio-v4").className,elements:[...document.querySelectorAll(".portfolio-v4 *")].filter(el=>el.getBoundingClientRect().right>innerWidth+1).slice(0,8).map(el=>({class:el.className,width:el.getBoundingClientRect().width,scroll:el.scrollWidth}))})));assert.equal(excess,false);};
await test('Layout studio previews animate, pause, cancel, apply and save without changing portfolio content',async(page,stored,writes)=>{
await page.goto(url+'/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');const card=page.getByRole('button',{name:'Preview Surrealism',exact:true});await card.click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:/^Creative gallery/}).click();const frame=page.frameLocator('iframe[title="Surrealism theme preview"]');await frame.locator('.pf-studio-projects-rail:not(.pf-static)').waitFor();await dialog.getByRole('button',{name:'Midnight',exact:true}).click();await frame.getByRole('heading',{name:'Anya Karri',exact:true}).waitFor();assert.equal(await frame.locator('.portfolio-v4').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(16, 21, 34)');await dialog.screenshot({path:path.join(output,'layout-studio-phone.png')});await dialog.getByRole('button',{name:'Pause preview',exact:true}).click();await frame.locator('.pf-static').waitFor();await dialog.getByRole('button',{name:'Play preview',exact:true}).click();await frame.locator('.pf-studio-projects-rail:not(.pf-static)').waitFor();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();assert.deepEqual(stored.layoutSettings,{});assert.equal(writes.length,0);
await card.click();await page.getByRole('dialog').getByRole('button',{name:/^Playful deck/}).click();await page.getByRole('button',{name:'Apply Theme',exact:true}).click();await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByText('Saved at',{exact:false}).waitFor();assert.equal(writes.length,1);assert.equal(stored.layoutSettings.projects,'cards');assert.equal(stored.motion,'expressive');assert.deepEqual(stored.projects,record.projects);assert.equal(stored.name,record.name);await page.reload();await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');await card.click();assert.equal(await page.getByRole('dialog').getByRole('button',{name:/^Playful deck/}).getAttribute('aria-pressed'),'true');
}, {width:390,height:900});
await test('An older preview service refuses unsupported layout saves and retains the recoverable experiment',async(page,stored,writes)=>{
await page.route('**/api/portfolio/capabilities',r=>r.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:'Not available'})}));await page.goto(url+'/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');await page.getByRole('button',{name:'Preview Surrealism',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:/^Creative gallery/}).click();await page.getByRole('button',{name:'Apply Theme',exact:true}).click();await page.getByRole('button',{name:'💾 Save Changes',exact:true}).click();await page.getByRole('alert').filter({hasText:'This preview cannot save custom layouts yet'}).waitFor();assert.equal(writes.length,0);assert.deepEqual(stored.layoutSettings,{});await page.waitForFunction(()=>JSON.parse(localStorage.getItem('porty:draft:v1:owner:one')||'{}').form?.layoutSettings?.projects==='rail');await page.reload();await page.getByRole('button',{name:'Recover draft',exact:true}).click();await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');await page.getByRole('button',{name:'Preview Surrealism',exact:true}).click();assert.equal(await page.getByRole('dialog').getByRole('button',{name:/^Creative gallery/}).getAttribute('aria-pressed'),'true');
});
await test('Interactive iframe supports Escape and restores the parent modal trigger focus',async page=>{
await page.goto(url+'/builder/one');await page.getByRole('button',{name:'Theme & Publish',exact:true}).click();await page.getByLabel('Search themes by name or style').fill('Surrealism');const trigger=page.getByRole('button',{name:'Preview Surrealism',exact:true});await trigger.click();await page.getByRole('dialog').getByRole('button',{name:'Interact with preview',exact:true}).click();await page.frameLocator('iframe[title="Surrealism theme preview"]').getByRole('button',{name:'Pause motion',exact:true}).focus();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await trigger.evaluate(el=>el===document.activeElement),true);
});
await test('Expressive hover tilt, visitor pause, dynamic reduced motion and reading progress work',async(page,stored)=>{
stored.theme='interactive-3d';await open(page);const media=page.locator('#pf-work .pf-project-media').first();await media.scrollIntoViewIfNeeded();const box=await media.boundingBox();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.4);await page.waitForFunction(()=>document.querySelector('#pf-work .pf-project-media').classList.contains('pf-tilting'));await page.getByRole('button',{name:'Pause motion',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.portfolio-v4').getAnimations({subtree:true}).filter(a=>a.playState==='running').length===0);assert.equal(await page.locator('.pf-tilting').count(),0);await page.getByRole('button',{name:'Resume motion',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Reduced motion',exact:true}).waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await page.emulateMedia({reducedMotion:'no-preference'});await page.getByRole('button',{name:'Pause motion',exact:true}).waitFor();await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.waitForFunction(()=>parseFloat(document.querySelector('.portfolio-v4').style.getPropertyValue('--pf-progress'))>0.5);await overflow(page);
});
await test('Atmosphere pauses offscreen and when the page is hidden',async(page,stored)=>{
stored.theme='space-explorer';await open(page);await page.locator('.portfolio-v4[data-ambient="running"]').waitFor();await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.locator('.portfolio-v4[data-ambient="paused"]').waitFor();await page.evaluate(()=>scrollTo(0,0));await page.locator('.portfolio-v4[data-ambient="running"]').waitFor();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await page.locator('.pf-resting').waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);
});
await test('Subtle motion has gentle reveals; Still mode keeps content and controls without animation',async(page,stored)=>{
stored.motion='subtle';await open(page);assert.equal(await page.locator('.pf-static').count(),0);await page.locator('#pf-work').scrollIntoViewIfNeeded();await page.locator('.pf-studio-entered').first().waitFor();assert.equal(await page.locator('.portfolio-v4').evaluate(el=>getComputedStyle(el).getPropertyValue('--pf-reveal-distance').trim()),'8px');stored.motion='none';await open(page);assert.equal(await page.locator('.pf-static').count(),1);assert.equal(await page.locator('#pf-work .pf-project').count(),3);assert.equal(await page.locator('.portfolio-v4').evaluate(el=>el.getAnimations({subtree:true}).length),0);
});
await test('Canvas cards drag, move by keyboard, reset and open actual projects',async(page,stored)=>{
stored.theme='infinite-canvas';await open(page);const card=page.getByRole('button',{name:'Arrange Community journal',exact:true});await card.scrollIntoViewIfNeeded();const initial=await card.getAttribute('style');await card.focus();await page.keyboard.press('ArrowRight');assert.notEqual(await card.getAttribute('style'),initial);const box=await card.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+box.height/2+30,{steps:5});await page.mouse.up();await page.getByRole('button',{name:'Reset board',exact:true}).click();assert.equal(await card.getAttribute('style'),initial);await card.focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>{const r=document.querySelector('#pf-work .pf-project').getBoundingClientRect();return r.top<innerHeight && r.bottom>0;});await page.getByRole('button',{name:'Reading view',exact:true}).click();assert.equal(await page.locator('.ex-playground').count(),0);assert.equal(await page.locator('#pf-work .pf-project').count(),3);await overflow(page);
});
await test('Canvas direct touch dragging changes positions without losing full project access',async(page,stored)=>{
stored.theme='infinite-canvas';await open(page);const card=page.getByRole('button',{name:'Arrange Community journal',exact:true});const initial=await card.getAttribute('style');await card.evaluate(el=>{const r=el.getBoundingClientRect(),id=9;el.setPointerCapture=()=>{};el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+20,clientY:r.y+20}));el.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+75,clientY:r.y+55}));el.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:id,pointerType:'touch',clientX:r.x+75,clientY:r.y+55}));});assert.notEqual(await card.getAttribute('style'),initial);assert.equal(await page.locator('#pf-work .pf-project-links a').count(),6);await overflow(page);
},{width:390,height:900},true);
await test('Pixel explorer responds to controls and counts only visited supplied project paths',async(page,stored)=>{
stored.theme='pixel-art';await open(page);const player=page.locator('.ex-pixel-player');const initial=await player.getAttribute('style');await page.getByRole('button',{name:'Move right',exact:true}).click();assert.notEqual(await player.getAttribute('style'),initial);await page.getByRole('button',{name:'Jump',exact:true}).click();assert.equal(await page.locator('.ex-pixel-jump').count(),1);await page.locator('.ex-pixel-paths').getByRole('link',{name:'◇ Community journal',exact:true}).click();await page.getByText('1 of 3 project paths explored',{exact:true}).waitFor();assert.equal(await page.locator('#pf-work .pf-project').count(),3);await page.locator('.ex-pixel-game').scrollIntoViewIfNeeded();await page.locator('.ex-pixel-game').screenshot({path:path.join(output,'pixel-explorer.png')});await overflow(page);
},{width:390,height:900});
await test('Terminal commands and cinema navigation point to supplied content',async(page,stored)=>{
stored.theme='terminal-os';await open(page);await page.getByLabel('Portfolio command',{exact:true}).fill('ls');await page.getByRole('button',{name:'Run command',exact:true}).click();assert.match(await page.locator('.ex-console-output').innerText(),/Community journal/);await page.getByRole('link',{name:'Open section',exact:false}).click();assert.equal(new URL(page.url()).hash,'#pf-work');await page.getByLabel('Portfolio command',{exact:true}).fill('delete everything');await page.getByRole('button',{name:'Run command',exact:true}).click();assert.match(await page.locator('.ex-console-output').innerText(),/Unknown command/);assert.equal(await page.locator('#pf-work .pf-project').count(),3);stored.theme='scroll-cinema';await open(page);const scene=page.getByRole('button',{name:'01 / Community journal',exact:true});await scene.click();assert.equal(await scene.getAttribute('aria-pressed'),'true');await overflow(page);
});
await test('All 41 themes accept four layout experiments on desktop and phone, retaining every destination',async(page,stored)=>{
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../../backend/themeCatalog.json')));
const layouts=[{hero:'centered',projects:'cards',spacing:'compact',typography:'bold',image:'square',hover:'tilt'},{hero:'split',projects:'spotlight',spacing:'airy',typography:'editorial',image:'wide',hover:'lift'},{hero:'centered',projects:'rail',spacing:'airy',typography:'mono',image:'rounded',hover:'tilt'},{}];
for(const theme of catalog.map(t=>t.id).filter(id=>!process.env.PORTY_LAYOUT_THEMES || process.env.PORTY_LAYOUT_THEMES.split(",").includes(id)))for(const layout of layouts)for(const width of [390,1440]){
 stored.theme=theme;stored.layoutSettings=layout;await page.setViewportSize({width,height:1000});await open(page);await overflow(page);assert.equal(await page.locator('#pf-work .pf-project').count(),3);
 if(layout.typography){const expected={bold:'Inter',editorial:'Georgia',mono:'JetBrains Mono'}[layout.typography];assert.ok(await page.locator('.portfolio-v4 h1').evaluate((el,font)=>getComputedStyle(el).fontFamily.includes(font),expected),theme+' typography override');}
 if(layout.hero==='centered')assert.equal(await page.locator('.pf-hero').evaluate(el=>getComputedStyle(el).textAlign),'center',theme+' centered introduction');
 if(layout.spacing)assert.equal(await page.locator('.pf-hero').evaluate(el=>getComputedStyle(el).paddingTop),layout.spacing==='compact'?(width===390?'42px':'58px'):(width===390?'76px':'120px'),theme+' spacing override');
 if(layout.image){const expected={square:'1 / 1',wide:'21 / 10',rounded:'4 / 3'}[layout.image];assert.equal(await page.locator('#pf-work .pf-project-media').first().evaluate(el=>getComputedStyle(el).aspectRatio),expected,theme+' image frame override');}
const links=await page.locator('#pf-work .pf-project-links a').evaluateAll(elements=>elements.map(el=>el.href).sort());assert.deepEqual(links,record.projects.flatMap(p=>[p.link,p.github]).sort());
 if(layout.projects==='rail'){const gallery=page.locator('#pf-work .pf-project-grid');assert.equal(await gallery.evaluate(el=>getComputedStyle(el).display),'flex');await page.getByRole('group',{name:'Horizontal gallery',exact:true}).getByRole('button',{name:'Next projects',exact:true}).click();assert.ok(await gallery.evaluate(el=>el.scrollWidth>el.clientWidth));}
 cases++;if(layout.projects==='rail' && ['surrealism','interactive-3d','pixel-art','scroll-cinema','scrapbook'].includes(theme))await page.screenshot({path:path.join(output,`${theme}-${width}.png`)});
}
}, {width:1440,height:1000},true);
console.log(`${passed} motion/interaction scenarios and ${cases} layout cases passed.`);
}finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e.stack);if(e.cause)console.error(e.cause.stack);process.exitCode=1;});
