import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { getPortfolioById, updatePortfolio } from "../../utils/api";
import { blank } from "../../hooks/usePortfolioForm";
export default function ProfileReuse({ portfolios, token, onUpdated }) {
  const navigate = useNavigate(); const [source,setSource] = useState(""); const [fields,setFields] = useState([]); const [targets,setTargets] = useState([]); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [message,setMessage] = useState("");
  const choices = [["name","Name"],["title","Role"],["about","Biography"],["avatarUrl","Portrait"],["skills","Skills"],["experience","Experience"],["contact","Contact information"],["socialLinks","Social links"],["resumeUrl","Resume link"]];
  const reuse = async propagate => { if(!source) return; setBusy(true);setError("");setMessage("");try { const result = await getPortfolioById(source,token); if(!propagate) { const content=Object.fromEntries(Object.keys(blank).map(key=>[key,result.data[key] ?? blank[key]])); navigate("/builder",{state:{resumeData:{...content,isPublic:false,showcaseOptIn:false,audience:""}}}); return; } const changes=Object.fromEntries(fields.map(key=>[key,result.data[key] ?? blank[key]])); const failures=[]; let saved=0; for(const id of targets.filter(id=>id!==source)){try {await updatePortfolio(id,{...changes,thumbnail:""},token);saved++;}catch(e){failures.push(`${portfolios.find(p=>p._id===id)?.name || id}: ${e.message}`);}} setMessage(`${saved} version${saved===1?"":"s"} updated. Public versions are updated at their existing links.`);setError(failures.join(" "));onUpdated(); } catch(e){setError(e.message);} finally{setBusy(false);} };
  return <details className="profile-reuse glass"><summary>Reuse profile information & create audience versions</summary><p>Create a private version from an existing portfolio, or choose individual fields to copy into selected versions. Projects and theme settings remain independent when copying profile fields.</p><label htmlFor="reuse-source">Source portfolio</label><select id="reuse-source" className="form-input" value={source} onChange={e=>{setSource(e.target.value);setTargets([]);}}><option value="">Choose a source</option>{portfolios.map(p=><option key={p._id} value={p._id}>{p.name}{p.audience?` · ${p.audience}`:""}</option>)}</select><button type="button" className="btn btn-secondary" disabled={!source || busy} onClick={()=>reuse(false)}>Create a private audience version</button>{source && <><fieldset><legend>Choose profile fields to copy</legend>{choices.map(([key,label])=><label key={key}><input type="checkbox" checked={fields.includes(key)} onChange={e=>setFields(previous=>e.target.checked?[...previous,key]:previous.filter(k=>k!==key))} /> {label}</label>)}</fieldset><fieldset><legend>Choose destination versions</legend>{portfolios.filter(p=>p._id!==source).map(p=><label key={p._id}><input type="checkbox" checked={targets.includes(p._id)} onChange={e=>setTargets(previous=>e.target.checked?[...previous,p._id]:previous.filter(k=>k!==p._id))} /> {p.name}{p.audience?` · ${p.audience}`:""} · {p.isPublic?"Public (changes go live)":"Private"}</label>)}</fieldset><p>Applying replaces the {fields.length} selected fields in {targets.length} selected versions. Their links stay the same. Portfolio covers are cleared and regenerated when each version is next saved.</p><button type="button" className="btn btn-primary" disabled={!fields.length || !targets.length || busy} onClick={()=>reuse(true)}>{busy?"Applying…":`Apply selected fields to ${targets.length} version${targets.length===1?"":"s"}`}</button></>}{message && <p role="status">{message}</p>}{error && <p className="form-error" role="alert">{error}</p>}</details>;
}
