import React, { useRef, useState } from "react";
import { readResume, resumeProposal } from "../../utils/resumeImport";
export default function ResumeImport({ form, onApply }) {
  const [text, setText] = useState(""); const [proposal, setProposal] = useState(null); const [selected, setSelected] = useState({}); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const generation = useRef(0);
  const review = value => { if (!value.trim()) { setError("No readable text was found. Scanned resumes need text recognition first. Paste the text or enter your details manually."); return; } setText(value); setProposal(resumeProposal(value)); setSelected({}); setError(""); };
  const load = async file => { if (!file) return; const request = ++generation.current; setBusy(true); setError(""); setProposal(null); try { const content = await readResume(file); if (request === generation.current) review(content); } catch(e) { if (request === generation.current) setError(e.message); } finally { if (request === generation.current) setBusy(false); } };
  const apply = () => { const next = {}; for (const key of Object.keys(selected).filter(k => selected[k])) { if (key === "email") next.contact = { ...form.contact, email: proposal.email }; else next[key] = proposal[key]; } onApply(next); setProposal(null); setSelected({}); };
  return <details className="resume-import"><summary>Start from a resume · optional</summary><p>Import PDF, Word (.docx), or text. Nothing is changed until you review and choose fields to apply. Your file is read on this device.</p><label htmlFor="resume-file">Choose resume</label><input id="resume-file" type="file" accept=".pdf,.docx,.txt" disabled={busy} onChange={e => { load(e.target.files[0]); e.target.value = ""; }} />{busy && <div role="status">Reading your resume… <button type="button" className="btn btn-secondary btn-sm" onClick={() => { generation.current++; setBusy(false); }}>Cancel</button></div>}
    <label htmlFor="resume-text">Or paste resume text</label><textarea id="resume-text" className="form-input" rows={6} maxLength={60000} value={text} onChange={e => setText(e.target.value)} /><button type="button" className="btn btn-secondary btn-sm" disabled={busy || !text.trim()} onClick={() => review(text)}>Review extracted information</button>{error && <p role="alert" className="form-error">{error}</p>}
    {proposal && <div className="ai-review" aria-label="Resume review"><h3>Review before applying</h3><p>Extraction may miss headings or split lines incorrectly. Check every suggestion. Your full text remains above for details that need manual entry. Selected fields replace their current values; unselected fields stay as they are.</p>{["name", "about", "email", "skills"].map(key => <div className="form-group" key={key}><label><input type="checkbox" checked={Boolean(selected[key])} onChange={e => setSelected({ ...selected, [key]: e.target.checked })} /> Apply {key}</label><label className="sr-only" htmlFor={`resume-${key}`}>Extracted {key}</label><textarea id={`resume-${key}`} className="form-input" rows={key === "about" ? 4 : 2} value={key === "skills" ? proposal.skills.join(", ") : proposal[key]} onChange={e => setProposal({ ...proposal, [key]: key === "skills" ? e.target.value.split(",").map(s => s.trim()) : e.target.value })} /></div>)}
      {proposal.projects.length > 0 && <fieldset><legend>Extracted projects</legend><label><input type="checkbox" checked={Boolean(selected.projects)} onChange={e => setSelected({ ...selected, projects: e.target.checked })} /> Replace current projects with these reviewed projects</label>{proposal.projects.map((p,i) => <div className="sub-card" key={i}><label htmlFor={`resume-project-${i}`}>Project {i+1} title</label><input id={`resume-project-${i}`} className="form-input" value={p.title} onChange={e => setProposal({ ...proposal, projects: proposal.projects.map((x,j) => j === i ? { ...x, title:e.target.value } : x) })} /><label htmlFor={`resume-description-${i}`}>Description</label><textarea id={`resume-description-${i}`} className="form-input" value={p.description} onChange={e => setProposal({ ...proposal, projects: proposal.projects.map((x,j) => j === i ? { ...x, description:e.target.value } : x) })} /></div>)}</fieldset>}
      <div className="review-actions"><button type="button" className="btn btn-primary btn-sm" disabled={!Object.values(selected).some(Boolean)} onClick={apply}>Apply selected information</button><button type="button" className="btn btn-secondary btn-sm" onClick={() => { setProposal(null); setSelected({}); }}>Dismiss import</button></div></div>}
  </details>;
}
