import React, { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { blank, usePortfolioForm } from "../hooks/usePortfolioForm";
import { readJSON, writeJSON } from "../utils/storage";
import ThemeFrame from "../components/builder/ThemeFrame";
import ResumeImport from "../components/builder/ResumeImport";
import THEME_REGISTRY from "../registry/themeRegistry";
import { trackStep } from "../utils/journey";
import LayoutStudio from "../components/builder/LayoutStudio";
export default function GuestTrialPage() {
  const { state } = useLocation();
  const initial = useState(() => readJSON("localStorage", "porty:guest:v1"))[0];
  const { form, set } = usePortfolioForm({ ...blank, ...(initial.value || {}), ...(state?.style || {}), isPublic: false });
  const [error, setError] = useState(initial.error || ""); const [device, setDevice] = useState("desktop"); const [goal, setGoal] = useState(""); const [personality, setPersonality] = useState("");
  useEffect(() => { trackStep("start"); }, []);
  useEffect(() => { const timer = setTimeout(() => setError(writeJSON("localStorage", "porty:guest:v1", form) || ""), 400); return () => clearTimeout(timer); }, [form]);
  const finish = () => { setError(writeJSON("localStorage", "porty:guest:v1", form) || ""); trackStep("preview"); };
  const project = form.projects[0] || { title: "", description: "", techStack: [], image: "", link: "", github: "" };
  return <main className="container trial-page"><h1>See your portfolio before you sign up</h1><p>Add your name, role and one project. Only your name and biography are required when you later save. Optional sections can wait.</p>{error && <p className="alert alert-error" role="alert">{error}</p>}<div className="trial-grid"><section><ResumeImport form={form} onApply={values => Object.entries(values).forEach(([key,value]) => set(key,value))} />{[["name","Your name","Alex Morgan"],["title","Your role","Student designer"],["about","A little about you","What are you learning or building?"]].map(([key,label,placeholder]) => <div className="form-group" key={key}><label htmlFor={`trial-${key}`}>{label}</label><textarea id={`trial-${key}`} className="form-input" rows={key === "about" ? 3 : 1} value={form[key]} placeholder={placeholder} onChange={e => set(key,e.target.value)} /></div>)}
    <div className="form-group"><label htmlFor="trial-project">Project title</label><input id="trial-project" className="form-input" value={project.title} onChange={e => set("projects", [{ ...project,title:e.target.value }, ...form.projects.slice(1)])} /></div><div className="form-group"><label htmlFor="trial-description">What did you contribute?</label><textarea id="trial-description" className="form-input" rows={3} value={project.description} onChange={e => set("projects", [{ ...project,description:e.target.value }, ...form.projects.slice(1)])} /></div>
    <details><summary>Find a direction · optional</summary><label htmlFor="trial-goal">Your goal</label><select id="trial-goal" className="form-input" value={goal} onChange={e => { setGoal(e.target.value); set("audience", e.target.value); }}><option value="">Skip for now</option><option>Find my first role</option><option>Attract freelance clients</option><option>Share creative work</option></select><label htmlFor="trial-personality">Your style</label><select id="trial-personality" className="form-input" value={personality} onChange={e => { setPersonality(e.target.value); if(e.target.value) set("theme",e.target.value); }}><option value="">Explore myself</option><option value="minimalist">Calm and precise</option><option value="maximalism">Bold and expressive</option><option value="scrapbook">Warm and personal</option></select></details>
    <label htmlFor="trial-theme">Explore all 41 themes</label><select id="trial-theme" className="form-input" value={form.theme} onChange={e => { set("theme",e.target.value); set("themeColors",{}); trackStep("preview"); }}>{Object.values(THEME_REGISTRY).map(t => <option value={t.id} key={t.id}>{t.name}</option>)}</select><LayoutStudio value={form.layoutSettings} motion={form.motion} onChange={v=>set("layoutSettings",v)} onMotion={v=>set("motion",v)} id="trial-studio" /><p>Your trial stays on this device and is never published automatically.</p><div className="review-actions"><Link className="btn btn-primary" to="/register" state={{from:{pathname:"/builder"}}} onClick={finish}>Create account & continue</Link><Link className="btn btn-secondary" to="/login" state={{from:{pathname:"/builder"}}} onClick={finish}>Sign in & continue</Link></div></section><section aria-label="Guest portfolio preview"><div className="review-actions"><button type="button" className="btn btn-secondary btn-sm" aria-pressed={device === "desktop"} onClick={() => setDevice("desktop")}>Desktop</button><button type="button" className="btn btn-secondary btn-sm" aria-pressed={device === "mobile"} onClick={() => setDevice("mobile")}>Phone</button></div><ThemeFrame data={form} device={device} height={640} /></section></div></main>;
}
