import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { forgotPassword, resetPassword } from "../utils/api";
export function RecoveryPage() {
  const [email,setEmail] = useState(""); const [otp,setOTP] = useState(""); const [password,setPassword] = useState(""); const [visible,setVisible] = useState(false); const [step,setStep] = useState("request"); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [cooldown,setCooldown] = useState(0); const [message,setMessage] = useState("");
  useEffect(() => { if(!cooldown) return; const timer=setTimeout(()=>setCooldown(n=>Math.max(0,n-1)),1000); return ()=>clearTimeout(timer); }, [cooldown]);
  const request = async () => { setBusy(true);setError("");try{const r=await forgotPassword(email);setMessage(r.message);setStep("reset");setCooldown(60);}catch(e){setError(e.message);}finally{setBusy(false);} };
  const submit = async e => { e.preventDefault(); if(step==="request") return request(); setBusy(true);setError("");try{const r=await resetPassword(email,otp,password);setMessage(r.message);setStep("done");}catch(e){setError(e.message);}finally{setBusy(false);} };
  return <main className="container trial-page" style={{maxWidth:520}}><h1>Recover your account</h1><p>Your saved portfolios and drafts are kept.</p>{error && <p className="alert alert-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}{step!=="done" && <form onSubmit={submit}><label htmlFor="recovery-email">Email</label><input id="recovery-email" className="form-input" type="email" autoComplete="email" required value={email} readOnly={step==="reset"} onChange={e=>setEmail(e.target.value)} />{step==="reset" && <><label htmlFor="recovery-code">Recovery code · expires in five minutes</label><input id="recovery-code" className="form-input" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={otp} onChange={e=>setOTP(e.target.value.replace(/\D/g,""))} /><label htmlFor="recovery-password">New password</label><input id="recovery-password" className="form-input" type={visible?"text":"password"} autoComplete="new-password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} /><button type="button" className="btn btn-ghost btn-sm" aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?"Hide password":"Show password"}</button><button type="button" className="btn btn-ghost btn-sm" disabled={cooldown>0 || busy} onClick={request}>{cooldown?`Resend in ${cooldown}s`:"Resend recovery code"}</button><button type="button" className="btn btn-ghost btn-sm" onClick={()=>{setStep("request");setOTP("");}}>Change email</button></>}<button type="submit" className="btn btn-primary" disabled={busy}>{busy?"Please wait…":step==="request"?"Send recovery code":"Reset password"}</button></form>}<Link to="/login">Back to sign in</Link></main>;
}
