// Effects preserve the native composition, type and frames of every theme.
export const THEME_EFFECTS = {
  minimalist: { name: "Measured lines", note: "Precise rule drawing and quiet index accents in the original Swiss grid.", reveal: ".swiss-ruler, .pf-section-heading" },
  "dark-luxe": { name: "Gilded light", note: "Gold reflections follow the light across the original serif gallery.", pointer: ".pf-project-media, .luxe-portrait" },
  scrapbook: { name: "Paper & tape", note: "Mounted photos settle like paper; a focused story unfolds like a handwritten note.", reveal: ".scrapbook-photo" },
  "product-showcase": { name: "Studio reflection", note: "Device frames catch a polished reflection around the case study.", pointer: ".product-device" },
  "y2k-aesthetic": { name: "Chrome sparkle", note: "Chrome highlights and slowly turning stars retain the playful browser windows." },
  editorial: { name: "Ink & margin", note: "Margin strokes and headline underlines bring the original publication to life.", reveal: ".pf-section-heading" },
  "neon-terminal": { name: "Phosphor trace", note: "A restrained CRT scan animates the developer workspace." },
  brutalist: { name: "Offset press", note: "Hard shadows compress and the oversized arrow snaps into place.", reveal: ".brutalist-arrow" },
  neumorphic: { name: "Soft press", note: "Soft controls compress into their surface beneath sculpted light.", pointer: ".neumorphic-introduction" },
  aurora: { name: "Northern light", note: "Slow translucent ribbons move behind the centred introduction." },
  kinetic: { name: "Type in motion", note: "The existing typographic entrance gains a moving directional rule.", reveal: ".kinetic-rule" },
  executive: { name: "Signature rule", note: "An accent line traces the business profile and career entries.", reveal: ".executive-overview, .pf-timeline-row" },
  "retro-wave": { name: "Sunset horizon", note: "The striped sun breathes above a travelling perspective grid." },
  organic: { name: "Botanical breeze", note: "A hand-drawn branch grows into view and leaves sway around the soft portrait.", reveal: ".pf-effect-art" },
  bento: { name: "Cell highlight", note: "Individual tiles gain a small corner trace and tactile focus response.", reveal: ".bento-tile" },
  "apple-vision": { name: "Prismatic glass", note: "Prismatic contours and a pointer-lit glass edge suit the rounded spatial panels.", pointer: ".pf-project-media" },
  blueprint: { name: "Drafting plot", note: "Construction lines draw like a plotted technical drawing.", reveal: ".pf-effect-art" },
  "cyberpunk-2077": { name: "Diagonal signal", note: "An angled signal sweeps through the cut-corner panels; focus triggers one short chromatic echo." },
  "ai-assistant": { name: "Conversation orbit", note: "Three dots orbit the guide; topic replies arrive as a short conversation beat." },
  "interactive-3d": { name: "Desk perspective", note: "The illustrated desk responds to pointer perspective while its text stays readable.", pointer: ".ex-desk svg" },
  "timeline-journey": { name: "Journey path", note: "A travelling path marker and finite milestone traces fit the existing career journey.", reveal: ".pf-timeline-row" },
  "dashboard-portfolio": { name: "Circuit activity", note: "A circuit route and panel outlines give the dashboard an instrument feel.", reveal: ".ex-counts > div" },
  "space-explorer": { name: "Orbital drift", note: "Stable stars, a slow planetary orbit and gentle depth preserve the mission atmosphere." },
  "infinite-canvas": { name: "Pinned ideas", note: "Pins and pencil connectors appear on the dotted board; dragging casts a deeper paper shadow." },
  storybook: { name: "Turning pages", note: "Page-edge light and a short page turn animate the chapter reader." },
  "spotify-wrapped": { name: "Rhythm & vinyl", note: "A graphic equalizer and a rotating record ring support the music-inspired stories." },
  "netflix-portfolio": { name: "Preview spotlight", note: "The horizontal collection gets focused poster zoom and a cinematic sweep." },
  "google-maps-portfolio": { name: "Route discovery", note: "An illustrated route traces between section pins without inventing geographic data.", reveal: ".pf-effect-art" },
  "comic-book": { name: "Panel impact", note: "Speed lines draw outward and comic panels press into their hard shadows.", reveal: ".pf-effect-art" },
  "terminal-os": { name: "Boot sequence", note: "A finite boot-bar sequence and an input cursor fit the actual command console.", reveal: ".pf-effect-art" },
  newspaper: { name: "Printing press", note: "Ink rules print across the newspaper; article headings gain a crisp underline.", reveal: ".pf-section-heading" },
  museum: { name: "Gallery lighting", note: "A softly aimed pool of light illuminates framed work as visitors browse.", pointer: ".pf-project-media" },
  "hacker-matrix": { name: "Code rain", note: "Opt-in code rain gains column depth and a terminal-style focus trace." },
  surrealism: { name: "Liquid orbit", note: "An eccentric ellipse slowly morphs around an impossible floating shape." },
  "pixel-art": { name: "Pixel weather", note: "Stepped clouds, pixel stars and jump controls animate the green game world." },
  maximalism: { name: "Collage burst", note: "Different stamped shapes orbit a layered burst, retaining the bold alternating frames." },
  "conceptual-sketch": { name: "Pencil study", note: "Loose pencil strokes draw over the ruled notebook and underline the project studies.", reveal: ".pf-effect-art" },
  bohemian: { name: "Woven sun", note: "A woven radial sun and swaying fringe complement the arched portrait." },
  victorian: { name: "Engraved flourish", note: "An engraved flourish draws once around the ornate double borders.", reveal: ".pf-effect-art" },
  "wabi-sabi": { name: "Ink & breath", note: "An imperfect ink circle settles quietly inside the existing uneven frames.", reveal: ".pf-effect-art" },
  "scroll-cinema": { name: "Moving aperture", note: "A film aperture opens once, with gentle depth inside the original widescreen images.", reveal: ".pf-effect-art, .pf-project-media" },
};
export function effectFor(theme) { const id = THEME_EFFECTS[theme] ? theme : "minimalist"; return { id, ...THEME_EFFECTS[id] }; }
